# Generated by Django 6.0.2 on 2026-02-13 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tenants", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="tenant",
            name="accent_color",
            field=models.CharField(
                default="#3b82f6", help_text="Hex color e.g. #3b82f6", max_length=7
            ),
        ),
        migrations.AddField(
            model_name="tenant",
            name="favicon",
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name="tenant",
            name="footer_text",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="tenant",
            name="logo",
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name="tenant",
            name="primary_color",
            field=models.CharField(
                default="#2563eb", help_text="Hex color e.g. #2563eb", max_length=7
            ),
        ),
        migrations.AddField(
            model_name="tenant",
            name="secondary_color",
            field=models.CharField(
                default="#1e3a8a", help_text="Hex color e.g. #1e3a8a", max_length=7
            ),
        ),
    ]
