# Generated by Django 6.0.2 on 2026-02-13 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tenants", "0002_tenant_accent_color_tenant_favicon_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="tenant",
            name="email_from_name",
            field=models.CharField(
                blank=True, max_length=100, verbose_name="From Name"
            ),
        ),
        migrations.AddField(
            model_name="tenant",
            name="email_host",
            field=models.CharField(
                blank=True,
                default="smtp.gmail.com",
                max_length=255,
                verbose_name="SMTP Host",
            ),
        ),
        migrations.AddField(
            model_name="tenant",
            name="email_password",
            field=models.CharField(
                blank=True, max_length=255, verbose_name="SMTP Password"
            ),
        ),
        migrations.AddField(
            model_name="tenant",
            name="email_port",
            field=models.IntegerField(default=587, verbose_name="SMTP Port"),
        ),
        migrations.AddField(
            model_name="tenant",
            name="email_use_tls",
            field=models.BooleanField(default=True, verbose_name="Use TLS"),
        ),
        migrations.AddField(
            model_name="tenant",
            name="email_username",
            field=models.CharField(
                blank=True, max_length=255, verbose_name="SMTP Username"
            ),
        ),
    ]
