# Generated by Django 6.0.2 on 2026-02-13 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tenants", "0003_tenant_email_from_name_tenant_email_host_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="tenant",
            name="about",
            field=models.TextField(blank=True, null=True, verbose_name="نبذة عنا"),
        ),
        migrations.AddField(
            model_name="tenant",
            name="address",
            field=models.CharField(
                blank=True, max_length=255, null=True, verbose_name="العنوان"
            ),
        ),
        migrations.AddField(
            model_name="tenant",
            name="city",
            field=models.CharField(
                blank=True, max_length=100, null=True, verbose_name="المدينة"
            ),
        ),
        migrations.AddField(
            model_name="tenant",
            name="email",
            field=models.EmailField(
                blank=True, max_length=254, null=True, verbose_name="البريد الإلكتروني"
            ),
        ),
        migrations.AddField(
            model_name="tenant",
            name="facebook",
            field=models.URLField(
                blank=True, max_length=255, null=True, verbose_name="فيسبوك"
            ),
        ),
        migrations.AddField(
            model_name="tenant",
            name="instagram",
            field=models.URLField(
                blank=True, max_length=255, null=True, verbose_name="انستقرام"
            ),
        ),
        migrations.AddField(
            model_name="tenant",
            name="map_url",
            field=models.URLField(
                blank=True, max_length=500, null=True, verbose_name="رابط الخريطة"
            ),
        ),
        migrations.AddField(
            model_name="tenant",
            name="phone",
            field=models.CharField(
                blank=True, max_length=20, null=True, verbose_name="رقم الهاتف"
            ),
        ),
        migrations.AddField(
            model_name="tenant",
            name="phone2",
            field=models.CharField(
                blank=True, max_length=20, null=True, verbose_name="رقم هاتف إضافي"
            ),
        ),
        migrations.AddField(
            model_name="tenant",
            name="snapchat",
            field=models.URLField(
                blank=True, max_length=255, null=True, verbose_name="سناب شات"
            ),
        ),
        migrations.AddField(
            model_name="tenant",
            name="tiktok",
            field=models.URLField(
                blank=True, max_length=255, null=True, verbose_name="تيك توك"
            ),
        ),
        migrations.AddField(
            model_name="tenant",
            name="twitter",
            field=models.URLField(
                blank=True, max_length=255, null=True, verbose_name="تويتر"
            ),
        ),
        migrations.AddField(
            model_name="tenant",
            name="whatsapp",
            field=models.CharField(
                blank=True, max_length=20, null=True, verbose_name="واتساب"
            ),
        ),
        migrations.AddField(
            model_name="tenant",
            name="working_hours",
            field=models.CharField(
                blank=True, max_length=100, null=True, verbose_name="ساعات العمل"
            ),
        ),
        migrations.AddField(
            model_name="tenant",
            name="youtube",
            field=models.URLField(
                blank=True, max_length=255, null=True, verbose_name="يوتيوب"
            ),
        ),
    ]
