# Generated by Django 6.0.2 on 2026-02-13 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "tenants",
            "0004_tenant_about_tenant_address_tenant_city_tenant_email_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="tenant",
            name="about_en",
            field=models.TextField(blank=True, null=True, verbose_name="About Us (EN)"),
        ),
        migrations.AddField(
            model_name="tenant",
            name="address_en",
            field=models.CharField(
                blank=True, max_length=255, null=True, verbose_name="Address (EN)"
            ),
        ),
        migrations.AddField(
            model_name="tenant",
            name="city_en",
            field=models.CharField(
                blank=True, max_length=100, null=True, verbose_name="City (EN)"
            ),
        ),
        migrations.AddField(
            model_name="tenant",
            name="footer_text_en",
            field=models.CharField(
                blank=True, max_length=255, null=True, verbose_name="Footer Text (EN)"
            ),
        ),
        migrations.AddField(
            model_name="tenant",
            name="working_hours_en",
            field=models.CharField(
                blank=True, max_length=100, null=True, verbose_name="Working Hours (EN)"
            ),
        ),
        migrations.AlterField(
            model_name="tenant",
            name="about",
            field=models.TextField(
                blank=True, null=True, verbose_name="نبذة عنا (عربي)"
            ),
        ),
        migrations.AlterField(
            model_name="tenant",
            name="address",
            field=models.CharField(
                blank=True, max_length=255, null=True, verbose_name="العنوان (عربي)"
            ),
        ),
        migrations.AlterField(
            model_name="tenant",
            name="city",
            field=models.CharField(
                blank=True, max_length=100, null=True, verbose_name="المدينة (عربي)"
            ),
        ),
        migrations.AlterField(
            model_name="tenant",
            name="footer_text",
            field=models.CharField(
                blank=True, max_length=255, null=True, verbose_name="نص الفوتر (عربي)"
            ),
        ),
        migrations.AlterField(
            model_name="tenant",
            name="working_hours",
            field=models.CharField(
                blank=True, max_length=100, null=True, verbose_name="ساعات العمل (عربي)"
            ),
        ),
    ]
