# Generated by Django 6.0.2 on 2026-02-13 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tenants", "0005_tenant_about_en_tenant_address_en_tenant_city_en_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="tenant",
            name="contact_person_name",
            field=models.CharField(
                blank=True, max_length=100, null=True, verbose_name="اسم المسؤول"
            ),
        ),
        migrations.AddField(
            model_name="tenant",
            name="contact_person_photo",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to="contact_photos/",
                verbose_name="صورة المسؤول",
            ),
        ),
    ]
