# Generated by Django 6.0.2 on 2026-02-16 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tenants", "0006_tenant_contact_person_name_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="tenant",
            name="favicon",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to="tenant_favicons/",
                verbose_name="أيقونة الموقع",
            ),
        ),
        migrations.AlterField(
            model_name="tenant",
            name="logo",
            field=models.ImageField(
                blank=True, null=True, upload_to="tenant_logos/", verbose_name="الشعار"
            ),
        ),
    ]
