# Generated by Django 6.0.2 on 2026-02-16 14:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tenants", "0007_alter_tenant_favicon_alter_tenant_logo"),
    ]

    operations = [
        migrations.CreateModel(
            name="TenantPhoneNumber",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "phone_number",
                    models.CharField(max_length=20, verbose_name="رقم الهاتف"),
                ),
                (
                    "phone_type",
                    models.CharField(
                        choices=[
                            ("general", "عام"),
                            ("sales", "مبيعات"),
                            ("support", "دعم فني"),
                            ("whatsapp", "واتساب"),
                            ("manager", "مدير"),
                            ("other", "أخرى"),
                        ],
                        default="general",
                        max_length=20,
                        verbose_name="نوع الرقم",
                    ),
                ),
                (
                    "label",
                    models.CharField(
                        blank=True,
                        help_text="مثل: قسم المبيعات، الفرع الرئيسي",
                        max_length=50,
                        verbose_name="تسمية إضافية",
                    ),
                ),
                (
                    "is_primary",
                    models.BooleanField(default=False, verbose_name="رقم رئيسي"),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="نشط")),
                ("order", models.IntegerField(default=0, verbose_name="الترتيب")),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="phone_numbers",
                        to="tenants.tenant",
                        verbose_name="الموقع",
                    ),
                ),
            ],
            options={
                "verbose_name": "رقم هاتف",
                "verbose_name_plural": "أرقام الهواتف",
                "ordering": ["order", "-is_primary", "phone_type"],
            },
        ),
    ]
