# Generated by Django 6.0.2 on 2026-02-16 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tenants", "0008_tenantphonenumber"),
    ]

    operations = [
        migrations.AddField(
            model_name="tenant",
            name="hero_image",
            field=models.ImageField(
                blank=True,
                help_text="صورة خلفية الصفحة الرئيسية",
                null=True,
                upload_to="tenant_hero/",
                verbose_name="صورة الخلفية الرئيسية",
            ),
        ),
    ]
