# Generated by Django 6.0.2 on 2026-02-19 11:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tenants", "0009_tenant_hero_image"),
    ]

    operations = [
        migrations.CreateModel(
            name="TenantHeroImage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "image",
                    models.ImageField(upload_to="tenant_hero/", verbose_name="الصورة"),
                ),
                (
                    "order",
                    models.PositiveIntegerField(default=0, verbose_name="الترتيب"),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="hero_images",
                        to="tenants.tenant",
                        verbose_name="الموقع",
                    ),
                ),
            ],
            options={
                "verbose_name": "صورة الهيرو",
                "verbose_name_plural": "صور الهيرو",
                "ordering": ["order"],
            },
        ),
    ]
