# Generated by Django 6.0.2 on 2026-03-03 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tenants", "0010_tenantheroimage"),
    ]

    operations = [
        migrations.AddField(
            model_name="tenant",
            name="body_bg_color",
            field=models.CharField(
                blank=True,
                default="#ffffff",
                help_text="Hex color for the page background e.g. #f9fafb. Leave blank for white.",
                max_length=7,
                verbose_name="Body Background Color",
            ),
        ),
    ]
