# Generated by Django 6.0.2 on 2026-03-03 21:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tenants", "0011_add_body_bg_color_to_tenant"),
    ]

    operations = [
        migrations.AddField(
            model_name="tenant",
            name="theme",
            field=models.CharField(
                choices=[
                    ("light", "فاتح (Light)"),
                    ("dark", "داكن (Dark)"),
                    ("custom", "مخصص (Custom Colors)"),
                ],
                default="light",
                help_text="اختر المظهر العام للموقع. اختر 'مخصص' لاستخدام الألوان المحددة أدناه.",
                max_length=10,
                verbose_name="ثيم الموقع",
            ),
        ),
        migrations.AlterField(
            model_name="tenant",
            name="accent_color",
            field=models.CharField(
                default="#3b82f6",
                help_text="Hex color e.g. #3b82f6 (used in Custom theme)",
                max_length=7,
            ),
        ),
        migrations.AlterField(
            model_name="tenant",
            name="body_bg_color",
            field=models.CharField(
                blank=True,
                default="#ffffff",
                help_text="Hex color for the page background (used in Custom theme).",
                max_length=7,
                verbose_name="Body Background Color",
            ),
        ),
        migrations.AlterField(
            model_name="tenant",
            name="primary_color",
            field=models.CharField(
                default="#2563eb",
                help_text="Hex color e.g. #2563eb (used in Custom theme)",
                max_length=7,
            ),
        ),
        migrations.AlterField(
            model_name="tenant",
            name="secondary_color",
            field=models.CharField(
                default="#1e3a8a",
                help_text="Hex color e.g. #1e3a8a (used in Custom theme)",
                max_length=7,
            ),
        ),
    ]
