# Generated by Django 6.0.2 on 2026-03-06 23:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tenants", "0013_add_desert_theme_choice"),
    ]

    operations = [
        migrations.AddField(
            model_name="tenant",
            name="telegram",
            field=models.URLField(
                blank=True, max_length=255, null=True, verbose_name="تيليجرام (رابط)"
            ),
        ),
        migrations.AddField(
            model_name="tenant",
            name="telegram_username",
            field=models.CharField(
                blank=True,
                help_text="ادخل اسم المستخدم بدون @ — سيُحوّل تلقائياً إلى رابط t.me/username",
                max_length=64,
                null=True,
                verbose_name="تيليجرام (اسم المستخدم)",
            ),
        ),
    ]
