# Generated by Django 6.0.2 on 2026-03-15 20:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tenants", "0014_tenant_telegram_tenant_telegram_username"),
    ]

    operations = [
        migrations.AddField(
            model_name="tenant",
            name="rate_aed",
            field=models.DecimalField(
                decimal_places=6,
                default=0.00272,
                max_digits=10,
                verbose_name="سعر الدرهم AED",
            ),
        ),
        migrations.AddField(
            model_name="tenant",
            name="rate_eur",
            field=models.DecimalField(
                decimal_places=6,
                default=0.00069,
                max_digits=10,
                verbose_name="سعر اليورو EUR",
            ),
        ),
        migrations.AddField(
            model_name="tenant",
            name="rate_sar",
            field=models.DecimalField(
                decimal_places=6,
                default=0.0025,
                max_digits=10,
                verbose_name="سعر الريال SAR",
            ),
        ),
        migrations.AddField(
            model_name="tenant",
            name="rate_usd",
            field=models.DecimalField(
                decimal_places=6,
                default=0.00067,
                max_digits=10,
                verbose_name="سعر الدولار USD",
            ),
        ),
    ]
