# Generated by Django 6.0.2 on 2026-03-19 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tenants", "0015_add_currency_rates"),
    ]

    operations = [
        migrations.AlterField(
            model_name="tenant",
            name="theme",
            field=models.CharField(
                choices=[
                    ("light", "فاتح (Light)"),
                    ("dark", "داكن (Dark)"),
                    ("desert", "🐪 صحراوي عربي (Desert Arabia)"),
                    ("custom", "مخصص (Custom Colors)"),
                    ("eid", "🎉 عيد (Eid Theme)"),
                ],
                default="light",
                help_text="اختر المظهر العام للموقع. 🐪 صحراوي: تصميم عربي بألوان الصحراء والجِمال. مخصص: يستخدم الألوان المحددة أدناه.",
                max_length=10,
                verbose_name="ثيم الموقع",
            ),
        ),
    ]
