# Generated by Django 6.0.2 on 2026-03-24 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tenants", "0018_tenant_ofleet_credentials"),
    ]

    operations = [
        migrations.AddField(
            model_name="tenant",
            name="ofleet_split_by_make",
            field=models.BooleanField(
                default=True,
                help_text="عند التفعيل: يتم إنشاء ملف PDF منفصل لكل ماركة. عند الإيقاف: ملف PDF واحد يشمل جميع السيارات.",
                verbose_name="تقسيم PDF حسب الماركة",
            ),
        ),
    ]
