# Generated by Django 6.0.2 on 2026-04-29 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0026_tenant_tagline'),
    ]

    operations = [
        migrations.AddField(
            model_name='tenant',
            name='billing_visible',
            field=models.BooleanField(default=False, help_text='عند التفعيل: تظهر صفحة الفوترة وروابطها لإداريي هذا الموقع.', verbose_name='إظهار الفوترة'),
        ),
    ]
