# Generated by Django 6.0.2 on 2026-04-29 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0027_tenant_billing_visible'),
    ]

    operations = [
        migrations.AddField(
            model_name='tenant',
            name='billing_amount_usd',
            field=models.DecimalField(decimal_places=2, default=400, help_text='المبلغ الذي يدفعه هذا الموقع شهرياً بالدولار الأمريكي. الافتراضي 400$.', max_digits=8, verbose_name='مبلغ الفوترة (USD)'),
        ),
    ]
