# Generated by Django 6.0.2 on 2026-04-30 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0028_tenant_billing_amount_usd'),
    ]

    operations = [
        migrations.AddField(
            model_name='tenant',
            name='template_theme',
            field=models.CharField(choices=[('default', 'Default (الافتراضي)'), ('luxury', '✨ Luxury (فخم — ذهبي/أسود)')], default='default', help_text='ثيم كامل يبدّل قوالب الموقع (HTML) كلياً، وليس مجرد ألوان. الافتراضي يستخدم القوالب القياسية.', max_length=20, verbose_name='ثيم القوالب'),
        ),
    ]
