# Generated by Django 6.0.2 on 2026-05-09 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0030_globalexchangerates'),
    ]

    operations = [
        migrations.AddField(
            model_name='tenant',
            name='show_hero',
            field=models.BooleanField(default=True, help_text='عند التعطيل تختفي قسم الهيرو من الصفحة الرئيسية ويُرفع المحتوى لأعلى.', verbose_name='إظهار الهيرو في الصفحة الرئيسية'),
        ),
    ]
