# Generated by Django 6.0.2 on 2026-05-09 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0031_add_show_hero'),
    ]

    operations = [
        migrations.AddField(
            model_name='tenant',
            name='show_watermark',
            field=models.BooleanField(default=True, help_text='عند التعطيل تختفي العلامة المائية (الشعار) المرتسمة فوق صور السيارات.', verbose_name='إظهار العلامة المائية على الصور'),
        ),
    ]
