# Generated by Django 6.0.2 on 2026-05-21 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0032_add_show_watermark'),
    ]

    operations = [
        migrations.AddField(
            model_name='tenant',
            name='show_auctions',
            field=models.BooleanField(default=True, help_text='عند التعطيل تختفي قسم سيارات المزاد من الصفحة الرئيسية وقوائم السيارات.', verbose_name='عرض سيارات المزاد'),
        ),
        migrations.AddField(
            model_name='tenant',
            name='show_encar',
            field=models.BooleanField(default=True, help_text='عند التعطيل تختفي قسم سيارات Encar (السيارات العادية المستوردة) من الصفحة الرئيسية وقوائم السيارات.', verbose_name='عرض سيارات Encar'),
        ),
        migrations.AddField(
            model_name='tenant',
            name='show_site_cars',
            field=models.BooleanField(default=True, help_text='عند التعطيل تختفي ‘سياراتنا‘ (سيارات الموقع الخاصة بك) من الصفحة الرئيسية، وتُخفى أزرار الإضافة في لوحة التحكم.', verbose_name='عرض ‘سياراتنا‘ والسماح بإضافتها'),
        ),
    ]
