# Generated by Django 6.0.2 on 2026-06-03 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0033_add_section_toggles'),
    ]

    operations = [
        migrations.AddField(
            model_name='tenant',
            name='import_calc_agent',
            field=models.PositiveIntegerField(default=2000, verbose_name='عمولة الوكيل (ر.س)'),
        ),
        migrations.AddField(
            model_name='tenant',
            name='import_calc_clearance',
            field=models.PositiveIntegerField(default=1500, verbose_name='التخليص الجمركي (ر.س)'),
        ),
        migrations.AddField(
            model_name='tenant',
            name='import_calc_duty_pct',
            field=models.DecimalField(decimal_places=2, default=5, max_digits=5, verbose_name='الرسوم الجمركية (%)'),
        ),
        migrations.AddField(
            model_name='tenant',
            name='import_calc_enabled',
            field=models.BooleanField(default=True, help_text='إظهار/إخفاء حاسبة تكلفة الاستيراد (الشحن والجمارك والضريبة) في صفحة تفاصيل السيارة.', verbose_name='عرض حاسبة تكلفة الاستيراد'),
        ),
        migrations.AddField(
            model_name='tenant',
            name='import_calc_inspection',
            field=models.PositiveIntegerField(default=500, verbose_name='الفحص (ر.س)'),
        ),
        migrations.AddField(
            model_name='tenant',
            name='import_calc_preyear',
            field=models.PositiveIntegerField(default=2021, verbose_name='سنة الموديل للرسوم الإضافية'),
        ),
        migrations.AddField(
            model_name='tenant',
            name='import_calc_preyear_extra',
            field=models.PositiveIntegerField(default=23000, verbose_name='رسوم جمركية إضافية للموديلات الأقدم (ر.س)'),
        ),
        migrations.AddField(
            model_name='tenant',
            name='import_calc_registration',
            field=models.PositiveIntegerField(default=1000, verbose_name='اللوحات والاستمارة (ر.س)'),
        ),
        migrations.AddField(
            model_name='tenant',
            name='import_calc_shipping',
            field=models.PositiveIntegerField(default=5000, verbose_name='تكلفة الشحن (ر.س)'),
        ),
        migrations.AddField(
            model_name='tenant',
            name='import_calc_vat_pct',
            field=models.DecimalField(decimal_places=2, default=15, max_digits=5, verbose_name='ضريبة القيمة المضافة (%)'),
        ),
    ]
