# Generated by Django 6.0.2 on 2026-06-08 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0034_tenant_import_calc_agent_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tenant',
            name='import_calc_shipping_large',
            field=models.PositiveIntegerField(default=7000, verbose_name='تكلفة الشحن - حجم كبير (ر.س)'),
        ),
        migrations.AddField(
            model_name='tenant',
            name='import_calc_shipping_small',
            field=models.PositiveIntegerField(default=4000, verbose_name='تكلفة الشحن - حجم صغير (ر.س)'),
        ),
        migrations.AlterField(
            model_name='tenant',
            name='import_calc_shipping',
            field=models.PositiveIntegerField(default=5000, verbose_name='تكلفة الشحن - حجم متوسط (ر.س)'),
        ),
    ]
