# Generated by Django 6.0.2 on 2026-06-08 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0035_tenant_import_calc_shipping_large_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tenant',
            name='import_calc_shipping',
            field=models.PositiveIntegerField(default=7800, verbose_name='تكلفة الشحن - حجم متوسط (ر.س)'),
        ),
        migrations.AlterField(
            model_name='tenant',
            name='import_calc_shipping_large',
            field=models.PositiveIntegerField(default=9200, verbose_name='تكلفة الشحن - حجم كبير (ر.س)'),
        ),
        migrations.AlterField(
            model_name='tenant',
            name='import_calc_shipping_small',
            field=models.PositiveIntegerField(default=6500, verbose_name='تكلفة الشحن - حجم صغير (ر.س)'),
        ),
    ]
