# Generated by Django 6.0.2 on 2026-06-10 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0036_alter_tenant_import_calc_shipping_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tenant',
            name='seo_description',
            field=models.CharField(blank=True, help_text='الوصف الذي يظهر تحت العنوان في جوجل (≤160 حرفاً)', max_length=320, null=True, verbose_name='وصف SEO'),
        ),
        migrations.AddField(
            model_name='tenant',
            name='seo_keywords',
            field=models.CharField(blank=True, help_text='كلمات مفصولة بفواصل — مدينتك واسم العلامات التي تبيعها', max_length=500, null=True, verbose_name='كلمات مفتاحية SEO'),
        ),
        migrations.AddField(
            model_name='tenant',
            name='seo_title',
            field=models.CharField(blank=True, help_text='عنوان الصفحة في نتائج البحث (≤60 حرفاً). مثال: استيراد سيارات كوريا - الرياض', max_length=70, null=True, verbose_name='عنوان SEO'),
        ),
    ]
