# Generated by Django 6.0.2 on 2026-06-10 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0037_tenant_seo_description_tenant_seo_keywords_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tenant',
            name='gsc_verification_token',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Google site verification token'),
        ),
    ]
