# Generated by Django 6.0.2 on 2026-06-11 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0039_alter_tenant_landing_design'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tenant',
            name='theme',
            field=models.CharField(choices=[('light', 'فاتح (Light)'), ('dark', 'داكن (Dark)'), ('desert', '🐪 صحراوي عربي (Desert Arabia)'), ('ocean', '🌊 بحري كوري (Korean Ocean)'), ('custom', 'مخصص (Custom Colors)'), ('eid', '🎉 عيد (Eid Theme)')], default='light', help_text='اختر المظهر العام للموقع. 🐪 صحراوي: تصميم عربي بألوان الصحراء والجِمال. مخصص: يستخدم الألوان المحددة أدناه.', max_length=10, verbose_name='ثيم الموقع'),
        ),
    ]
