# Generated by Django 6.0.2 on 2026-06-11 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0040_alter_tenant_theme'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tenant',
            name='template_theme',
            field=models.CharField(choices=[('default', 'Default (الافتراضي)'), ('luxury', '✨ Luxury (فخم — ذهبي/أسود)'), ('modern', '🚀 Modern (عصري — كوري حديث)')], default='default', help_text='ثيم كامل يبدّل قوالب الموقع (HTML) كلياً، وليس مجرد ألوان. الافتراضي يستخدم القوالب القياسية.', max_length=20, verbose_name='ثيم القوالب'),
        ),
    ]
