# Generated by Django 6.0.2 on 2026-06-12 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0041_alter_tenant_template_theme'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tenant',
            name='accent_color',
            field=models.CharField(default='#3b82f6', help_text='Hex color e.g. #3b82f6 (used in Custom theme; in the Modern template theme it is the second color of the brand gradient — leave at default for the standard cyan)', max_length=7),
        ),
    ]
