# Generated by Django 6.0.2 on 2026-06-12 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0042_alter_tenant_accent_color'),
    ]

    operations = [
        migrations.AddField(
            model_name='tenant',
            name='import_calc_countries',
            field=models.JSONField(blank=True, default=list, verbose_name='دول إضافية لحاسبة الاستيراد'),
        ),
    ]
