# Generated by Django 6.0.2 on 2026-06-14 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0043_tenant_import_calc_countries'),
    ]

    operations = [
        migrations.AddField(
            model_name='tenant',
            name='is_active',
            field=models.BooleanField(default=True, help_text="عند إلغاء التفعيل يظهر للزوار صفحة 'الموقع غير متاح حالياً' مع الحفاظ على كامل البيانات. موظفو الموقع المسجّلون يمكنهم الدخول لإعادة التفعيل.", verbose_name='الموقع مُفعّل'),
        ),
    ]
