# Generated by Django 6.0.2 on 2026-06-15 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0046_tenant_site_font'),
    ]

    operations = [
        migrations.AddField(
            model_name='tenant',
            name='show_accessories',
            field=models.BooleanField(default=True, help_text='إظهار/إخفاء صفحة ‘الإكسسوارات‘ ورابطها في القائمة للزوار.', verbose_name='عرض صفحة الإكسسوارات'),
        ),
        migrations.AddField(
            model_name='tenant',
            name='show_parts',
            field=models.BooleanField(default=True, help_text='إظهار/إخفاء صفحة ‘قطع الغيار‘ ورابطها في القائمة للزوار.', verbose_name='عرض صفحة قطع الغيار'),
        ),
    ]
