# Generated by Django 6.0.2 on 2026-06-16 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0048_alter_tenant_site_font'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tenant',
            name='site_font',
            field=models.CharField(blank=True, choices=[('', 'افتراضي الثيم (Theme default)'), ('cairo', 'Cairo — كايرو'), ('tajawal', 'Tajawal — طجوال'), ('almarai', 'Almarai — المراعي'), ('el-messiri', 'El Messiri — المسيري'), ('changa', 'Changa — تشانغا'), ('readex-pro', 'Readex Pro — ريدكس'), ('noto-kufi', 'Noto Kufi — نوتو كوفي'), ('ibm-plex-ar', 'IBM Plex Arabic'), ('rubik', 'Rubik — روبيك'), ('markazi', 'Markazi — مركزي'), ('tahoma', 'Tahoma — تاهوما'), ('roboto', 'Roboto — روبوتو'), ('raleway', 'Raleway — رالواي'), ('ubuntu', 'Ubuntu — أوبونتو')], default='', help_text='خط عربي/لاتيني يُطبّق على كامل الموقع لكل الزوار. اتركه فارغاً لاستخدام الخط الافتراضي للثيم.', max_length=20, verbose_name='خط الموقع'),
        ),
    ]
