# Generated by Django 6.0.2 on 2026-06-17 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0049_alter_tenant_site_font'),
    ]

    operations = [
        migrations.AddField(
            model_name='tenant',
            name='ticker_color',
            field=models.CharField(blank=True, default='#dc2626', max_length=20, verbose_name='لون نص الشريط'),
        ),
        migrations.AddField(
            model_name='tenant',
            name='ticker_enabled',
            field=models.BooleanField(default=False, help_text='إظهار شريط إعلانات متحرك أعلى الموقع (مزادات، مبيعات، عروض…).', verbose_name='شريط الإعلانات المتحرك'),
        ),
        migrations.AddField(
            model_name='tenant',
            name='ticker_text',
            field=models.TextField(blank=True, default='', help_text='اكتب كل إعلان في سطر مستقل؛ تظهر الأسطر متتابعة في الشريط مفصولة بخط فاصل.', verbose_name='نص الشريط المتحرك'),
        ),
    ]
