# Generated by Django 6.0.2 on 2026-06-17 12:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0050_tenant_ticker_color_tenant_ticker_enabled_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tenant',
            name='how_we_work_title',
            field=models.CharField(blank=True, default='', help_text='اتركه فارغاً لاستخدام العنوان الافتراضي «كيف نعمل؟».', max_length=120, verbose_name='عنوان قسم «كيف نعمل»'),
        ),
        migrations.AddField(
            model_name='tenant',
            name='show_how_we_work',
            field=models.BooleanField(default=True, help_text='إظهار/إخفاء قسم خطوات العمل في الصفحة الرئيسية.', verbose_name='عرض قسم «كيف نعمل»'),
        ),
        migrations.CreateModel(
            name='TenantWorkStep',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('icon', models.CharField(blank=True, default='', help_text='إيموجي أو رمز قصير يظهر أعلى البطاقة، مثل 🚗 أو 📋 أو 1.', max_length=40, verbose_name='الأيقونة')),
                ('title', models.CharField(max_length=120, verbose_name='العنوان')),
                ('description', models.TextField(blank=True, default='', verbose_name='الوصف')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='الترتيب')),
                ('is_active', models.BooleanField(default=True, verbose_name='مُفعّل')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='work_steps', to='tenants.tenant', verbose_name='الموقع')),
            ],
            options={
                'verbose_name': 'خطوة عمل',
                'verbose_name_plural': 'خطوات «كيف نعمل»',
                'ordering': ['order', 'id'],
            },
        ),
    ]
