# Generated by Django 6.0.2 on 2026-06-17 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0051_tenant_how_we_work_title_tenant_show_how_we_work_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tenantheroimage',
            name='link_url',
            field=models.CharField(blank=True, default='', help_text='عند الضغط على هذه الصورة في الشريحة يتم الانتقال إلى هذا الرابط (اتركه فارغاً لتعطيل الرابط).', max_length=500, verbose_name='رابط الصورة'),
        ),
    ]
