# Generated by Django 6.0.2 on 2026-06-17 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0052_tenantheroimage_link_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='tenantheroimage',
            name='description',
            field=models.TextField(blank=True, default='', help_text='نص وصفي يظهر تحت العنوان (اختياري).', verbose_name='وصف الشريحة'),
        ),
        migrations.AddField(
            model_name='tenantheroimage',
            name='title',
            field=models.CharField(blank=True, default='', help_text='عنوان يظهر فوق الصورة (اختياري).', max_length=160, verbose_name='عنوان الشريحة'),
        ),
        migrations.AlterField(
            model_name='tenantheroimage',
            name='link_url',
            field=models.CharField(blank=True, default='', help_text='الصفحة التي يفتحها زر الإجراء على هذه الشريحة (اتركه فارغاً لإخفاء الزر).', max_length=500, verbose_name='رابط الشريحة (زر الإجراء)'),
        ),
    ]
