# Generated by Django 6.0.2 on 2026-06-19 15:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0054_tenant_owner'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='tenant',
            name='owner',
            field=models.ForeignKey(blank=True, help_text='حساب المستخدم (في القاعدة العامة) الذي يملك هذا الموقع.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='owned_tenants', to=settings.AUTH_USER_MODEL, verbose_name='مالك الموقع'),
        ),
        migrations.AlterField(
            model_name='tenant',
            name='template_theme',
            field=models.CharField(choices=[('default', 'Default (الافتراضي)'), ('luxury', '✨ Luxury (فخم — ذهبي/أسود)'), ('modern', '🚀 Modern (عصري — كوري حديث)'), ('glassy', '🔮 Glassy (زجاجي — داكن متوهّج)'), ('general', '🚗 General (جنرال — أبيض كحلي/أحمر)')], default='default', help_text='ثيم كامل يبدّل قوالب الموقع (HTML) كلياً، وليس مجرد ألوان. الافتراضي يستخدم القوالب القياسية.', max_length=20, verbose_name='ثيم القوالب'),
        ),
    ]
