# Generated by Django 6.0.2 on 2026-06-20 10:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0055_alter_tenant_owner_alter_tenant_template_theme'),
    ]

    operations = [
        migrations.CreateModel(
            name='TenantSalesPerson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='الاسم')),
                ('role', models.CharField(blank=True, default='', help_text='مثل: مبيعات، خدمة العملاء', max_length=80, verbose_name='المسمّى')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='sales_people/', verbose_name='الصورة')),
                ('whatsapp', models.CharField(blank=True, default='', help_text='مع رمز الدولة، مثال: 821012345678', max_length=30, verbose_name='واتساب')),
                ('phone', models.CharField(blank=True, default='', max_length=30, verbose_name='هاتف')),
                ('is_active', models.BooleanField(default=True, verbose_name='نشط')),
                ('order', models.IntegerField(default=0, verbose_name='الترتيب')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sales_people', to='tenants.tenant', verbose_name='الموقع')),
            ],
            options={
                'verbose_name': 'مندوب مبيعات',
                'verbose_name_plural': 'مندوبو المبيعات',
                'ordering': ['order', 'id'],
            },
        ),
    ]
