# Generated by Django 6.0.2 on 2026-06-20 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0056_tenantsalesperson'),
    ]

    operations = [
        migrations.AddField(
            model_name='tenant',
            name='commercial_registration',
            field=models.CharField(blank=True, default='', max_length=50, verbose_name='رقم السجل التجاري'),
        ),
        migrations.AddField(
            model_name='tenant',
            name='cr_barcode',
            field=models.ImageField(blank=True, help_text='صورة الباركود/الكود QR للسجل التجاري', null=True, upload_to='cr_barcodes/', verbose_name='باركود السجل التجاري'),
        ),
    ]
