# Generated by Django 6.0.2 on 2026-06-20 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0057_tenant_commercial_registration_tenant_cr_barcode'),
    ]

    operations = [
        migrations.AddField(
            model_name='tenant',
            name='whatsapp_channel',
            field=models.URLField(blank=True, help_text='رابط قناة الواتساب، مثال: https://whatsapp.com/channel/xxxx', max_length=255, null=True, verbose_name='قناة واتساب (رابط)'),
        ),
    ]
