# Generated by Django 6.0.2 on 2026-06-23 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0058_tenant_whatsapp_channel'),
    ]

    operations = [
        migrations.AddField(
            model_name='tenant',
            name='happycar_password',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='كلمة مرور HappyCar'),
        ),
        migrations.AddField(
            model_name='tenant',
            name='happycar_username',
            field=models.CharField(blank=True, default='', max_length=150, verbose_name='اسم مستخدم HappyCar'),
        ),
    ]
