# Generated by Django 6.0.2 on 2026-07-01 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0059_tenant_happycar_password_tenant_happycar_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='tenant',
            name='telegram_chat_id',
            field=models.CharField(blank=True, default='', max_length=32, verbose_name='Telegram chat id (bot)'),
        ),
    ]
