# Generated by Django 6.0.2 on 2026-07-02 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0060_tenant_telegram_chat_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='tenant',
            name='contract_bank',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='المصرف'),
        ),
        migrations.AddField(
            model_name='tenant',
            name='contract_clearance_license',
            field=models.CharField(blank=True, default='', max_length=60, verbose_name='رقم ترخيص التخليص'),
        ),
        migrations.AddField(
            model_name='tenant',
            name='contract_clearance_org',
            field=models.CharField(blank=True, default='', max_length=200, verbose_name='مؤسسة التخليص الجمركي'),
        ),
        migrations.AddField(
            model_name='tenant',
            name='contract_commission',
            field=models.CharField(blank=True, default='', max_length=60, verbose_name='مبلغ العمولة (نص)'),
        ),
        migrations.AddField(
            model_name='tenant',
            name='contract_default_port',
            field=models.CharField(blank=True, default='جدة', max_length=100, verbose_name='ميناء الوصول (افتراضي)'),
        ),
        migrations.AddField(
            model_name='tenant',
            name='contract_default_region',
            field=models.CharField(choices=[('korea', 'كوريا الجنوبية'), ('china', 'الصين'), ('usa', 'الولايات المتحدة')], default='korea', max_length=10, verbose_name='بلد المصدر (افتراضي)'),
        ),
        migrations.AddField(
            model_name='tenant',
            name='contract_email',
            field=models.CharField(blank=True, default='', max_length=120, verbose_name='بريد العقد'),
        ),
        migrations.AddField(
            model_name='tenant',
            name='contract_enabled',
            field=models.BooleanField(default=False, verbose_name='تفعيل عقد المشتري'),
        ),
        migrations.AddField(
            model_name='tenant',
            name='contract_import_days',
            field=models.CharField(blank=True, default='45 إلى 60', max_length=40, verbose_name='مدة الاستيراد المتوقعة (أيام)'),
        ),
        migrations.AddField(
            model_name='tenant',
            name='contract_party1',
            field=models.CharField(blank=True, default='', max_length=200, verbose_name='الطرف الأول (اسم/جهة)'),
        ),
        migrations.AddField(
            model_name='tenant',
            name='contract_phone',
            field=models.CharField(blank=True, default='', max_length=30, verbose_name='هاتف العقد'),
        ),
        migrations.AddField(
            model_name='tenant',
            name='contract_stamp',
            field=models.ImageField(blank=True, null=True, upload_to='tenant_contract/', verbose_name='ختم العقد'),
        ),
    ]
