# Generated by Django 6.0.2 on 2026-07-02 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0061_tenant_contract_bank_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tenant',
            name='auction_api_base',
            field=models.URLField(blank=True, default='', max_length=255, verbose_name='رابط خادم المزادات المباشرة'),
        ),
    ]
