# Generated by Django 6.0.2 on 2026-07-04 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0062_tenant_auction_api_base'),
    ]

    operations = [
        migrations.AddField(
            model_name='tenant',
            name='catalog_filter',
            field=models.JSONField(blank=True, default=dict, verbose_name='فلترة الكتالوج'),
        ),
    ]
