# Generated by Django 6.0.2 on 2026-07-08 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0063_tenant_catalog_filter'),
    ]

    operations = [
        migrations.AddField(
            model_name='tenant',
            name='price_markup_pct',
            field=models.DecimalField(decimal_places=2, default=0, help_text='نسبة تُضاف إلى أسعار السيارات المعروضة على موقعك (مثال: 5 تعني +5%).', max_digits=5, verbose_name='نسبة الزيادة على السعر (%)'),
        ),
    ]
