# Generated by Django 6.0.2 on 2026-07-08 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0064_tenant_price_markup_pct'),
    ]

    operations = [
        migrations.AddField(
            model_name='tenant',
            name='label_auctions',
            field=models.CharField(blank=True, default='', max_length=40, verbose_name='تسمية «المزادات»'),
        ),
        migrations.AddField(
            model_name='tenant',
            name='label_encar',
            field=models.CharField(blank=True, default='', max_length=40, verbose_name='تسمية «السيارات» (Encar)'),
        ),
        migrations.AddField(
            model_name='tenant',
            name='label_sitecars',
            field=models.CharField(blank=True, default='', max_length=40, verbose_name='تسمية «سياراتنا»'),
        ),
    ]
