# Generated by Django 6.0.2 on 2026-07-08 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0065_tenant_label_auctions_tenant_label_encar_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tenant',
            name='import_calc_show_agent',
            field=models.BooleanField(default=True, verbose_name='إظهار عمولة الوكيل في الحاسبة'),
        ),
        migrations.AddField(
            model_name='tenant',
            name='import_calc_show_clearance',
            field=models.BooleanField(default=True, verbose_name='إظهار التخليص الجمركي في الحاسبة'),
        ),
        migrations.AddField(
            model_name='tenant',
            name='import_calc_show_duty',
            field=models.BooleanField(default=True, verbose_name='إظهار الرسوم الجمركية في الحاسبة'),
        ),
        migrations.AddField(
            model_name='tenant',
            name='import_calc_show_extra',
            field=models.BooleanField(default=True, verbose_name='إظهار الرسوم الإضافية (موديل أقدم) في الحاسبة'),
        ),
        migrations.AddField(
            model_name='tenant',
            name='import_calc_show_inspection',
            field=models.BooleanField(default=True, verbose_name='إظهار الفحص في الحاسبة'),
        ),
        migrations.AddField(
            model_name='tenant',
            name='import_calc_show_registration',
            field=models.BooleanField(default=True, verbose_name='إظهار اللوحات والاستمارة في الحاسبة'),
        ),
        migrations.AddField(
            model_name='tenant',
            name='import_calc_show_shipping',
            field=models.BooleanField(default=True, verbose_name='إظهار الشحن في الحاسبة'),
        ),
        migrations.AddField(
            model_name='tenant',
            name='import_calc_show_vat',
            field=models.BooleanField(default=True, verbose_name='إظهار ضريبة القيمة المضافة في الحاسبة'),
        ),
    ]
