# Generated by Django 6.0.2 on 2026-07-09 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0066_tenant_import_calc_show_agent_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tenant',
            name='import_calc_show_sa',
            field=models.BooleanField(default=True, verbose_name='إظهار السعودية كوجهة في الحاسبة'),
        ),
    ]
