# Generated by Django 6.0.2 on 2026-07-09 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0069_alter_tenant_template_theme'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tenant',
            name='template_theme',
            field=models.CharField(choices=[('default', 'Default (الافتراضي)'), ('luxury', '✨ Luxury (فخم — ذهبي/أسود)'), ('modern', '🚀 Modern (عصري — كوري حديث)'), ('glassy', '🔮 Glassy (زجاجي — داكن متوهّج)'), ('general', '🚗 General (جنرال — أبيض كحلي/أحمر)'), ('editorial', '📰 Editorial (مجلة — أبيض/أسود/قرمزي)'), ('desert', '🏜️ Desert (صحراوي — رملي دافئ)'), ('market', '🛒 Market (سوق — بحث أولاً، أخضر)')], default='default', help_text='ثيم كامل يبدّل قوالب الموقع (HTML) كلياً، وليس مجرد ألوان. الافتراضي يستخدم القوالب القياسية.', max_length=20, verbose_name='ثيم القوالب'),
        ),
    ]
