# Generated by Django 6.0.2 on 2026-07-10 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0070_alter_tenant_template_theme'),
    ]

    operations = [
        migrations.AddField(
            model_name='tenant',
            name='custom_currencies',
            field=models.JSONField(blank=True, default=list, verbose_name='عملات إضافية'),
        ),
    ]
