# Generated by Django 6.0.2 on 2026-07-10 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0071_tenant_custom_currencies'),
    ]

    operations = [
        migrations.AddField(
            model_name='tenant',
            name='import_calc_sa_fees',
            field=models.JSONField(blank=True, default=list, verbose_name='رسوم إضافية للحاسبة (السعودية)'),
        ),
    ]
