# Generated by Django 6.0.2 on 2026-07-10 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0072_tenant_import_calc_sa_fees'),
    ]

    operations = [
        migrations.AddField(
            model_name='tenant',
            name='import_calc_config',
            field=models.JSONField(blank=True, default=list, verbose_name='إعداد الحاسبة (ديناميكي)'),
        ),
    ]
