# Generated by Django 6.0.2 on 2026-07-10 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0075_alter_tenant_template_theme'),
    ]

    operations = [
        migrations.AddField(
            model_name='tenant',
            name='dashboard_themes',
            field=models.JSONField(blank=True, default=list, verbose_name='الثيمات المتاحة في لوحة التحكم'),
        ),
    ]
