# Generated by Django 6.0.2 on 2026-07-11 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0076_tenant_dashboard_themes'),
    ]

    operations = [
        migrations.AddField(
            model_name='tenant',
            name='telegram_chat_name',
            field=models.CharField(blank=True, default='', max_length=128, verbose_name='Telegram المتصل (اسم)'),
        ),
    ]
