# Generated by Django 6.0.2 on 2026-07-16 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0077_tenant_telegram_chat_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='tenant',
            name='telegram_group',
            field=models.URLField(blank=True, help_text='رابط مجموعة تيليجرام، مثال: https://t.me/xxxx', max_length=255, null=True, verbose_name='مجموعة تيليجرام (رابط)'),
        ),
        migrations.AddField(
            model_name='tenant',
            name='whatsapp_group',
            field=models.URLField(blank=True, help_text='رابط مجموعة الواتساب، مثال: https://chat.whatsapp.com/xxxx', max_length=255, null=True, verbose_name='مجموعة واتساب (رابط)'),
        ),
        migrations.AlterField(
            model_name='tenant',
            name='telegram',
            field=models.URLField(blank=True, max_length=255, null=True, verbose_name='قناة تيليجرام (رابط)'),
        ),
    ]
