# Generated by Django 6.0.2 on 2026-07-17 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0078_tenant_telegram_group_tenant_whatsapp_group_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tenant',
            name='show_japan_market',
            field=models.BooleanField(default=False, help_text='عند التفعيل يظهر تبويب «سيارات يابانية» (سوق كارسنسر الياباني) في قوائم السيارات. معطّل افتراضياً.', verbose_name='عرض السيارات اليابانية'),
        ),
    ]
