# Generated by Django 6.0.2 on 2026-07-17 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0079_tenant_show_japan_market'),
    ]

    operations = [
        migrations.AddField(
            model_name='tenant',
            name='enabled_markets',
            field=models.JSONField(blank=True, default=list, help_text='أسماء فئات الأسواق التي تظهر كتبويبات لهذا الموقع (مثل japan_market). فارغ = لا شيء.', verbose_name='الأسواق المفعّلة'),
        ),
    ]
