# Generated by Django 6.0.2 on 2026-07-19 12:21

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0080_tenant_enabled_markets'),
    ]

    operations = [
        migrations.AddField(
            model_name='tenant',
            name='auction_grace_hours',
            field=models.IntegerField(default=0, help_text='عدد الساعات التي تبقى فيها سيارة المزاد ظاهرة بعد موعد المزاد. 0 = تختفي فور انتهاء الموعد، 24 = تبقى يوماً إضافياً، وبالسالب تختفي قبل الموعد. يؤثر على هذا الموقع فقط.', validators=[django.core.validators.MinValueValidator(-168), django.core.validators.MaxValueValidator(720)], verbose_name='مهلة إخفاء سيارات المزاد (ساعات)'),
        ),
    ]
