# Generated by Django 6.0.2 on 2026-07-19 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0081_tenant_auction_grace_hours'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tenant',
            name='auction_grace_hours',
        ),
        migrations.AddField(
            model_name='tenant',
            name='auction_end_time',
            field=models.TimeField(blank=True, help_text='الوقت الذي يظهر كموعد انتهاء المزاد على موقعك (نفس تاريخ المزاد، بهذا الوقت). اتركه فارغاً لعرض الوقت الأصلي كما هو.', null=True, verbose_name='وقت انتهاء المزاد'),
        ),
    ]
