"""Translate the car enum vocabularies (colors, fuels, transmissions, body
types, car models, addresses, options) to additional target languages and emit
`cars/utils_i18n.py` containing parallel dicts (`colors_dict_es`, `colors_dict_ru`,
etc.).

Usage:
    GOOGLE_TRANSLATE_API_KEY=... python manage.py translate_enums
    python manage.py translate_enums --target es,ru --dry-run

Idempotent: translations are cached in the same `.translations_cache.json` that
`translate_templates` uses, under a separate `_en_<target>` section (because the
source language here is English, not Arabic).
"""

from __future__ import annotations

import html
import json
import os
from pathlib import Path
from pprint import pformat

import requests
from django.conf import settings
from django.core.management.base import BaseCommand, CommandError

from cars.utils import (
    OPTION_TRANSLATIONS,
    address_en,
    body_types_dict,
    car_models_dict,
    colors_dict,
    fuel_types_dict,
    transmission_types_dict,
)


CACHE_FILE = Path(settings.BASE_DIR) / ".translations_cache.json"
OUTPUT_FILE = Path(settings.BASE_DIR) / "cars" / "utils_i18n.py"
GT_URL = "https://translation.googleapis.com/language/translate/v2"
BATCH_SIZE = 100


class Command(BaseCommand):
    help = "Translate car enum vocabularies to target languages and emit cars/utils_i18n.py."

    def add_arguments(self, parser):
        parser.add_argument("--target", default="es,ru")
        parser.add_argument("--api-key", default=None)
        parser.add_argument("--dry-run", action="store_true")

    def handle(self, *args, **opts):
        targets = [t.strip() for t in opts["target"].split(",") if t.strip()]
        api_key = opts["api_key"] or os.environ.get("GOOGLE_TRANSLATE_API_KEY")
        if not api_key:
            raise CommandError("Provide --api-key or set GOOGLE_TRANSLATE_API_KEY.")

        cache = self._load_cache()

        # Collect every unique English source string.
        strings: set[str] = set()
        for d in (colors_dict, fuel_types_dict, transmission_types_dict,
                  body_types_dict, car_models_dict):
            for k in d:
                if isinstance(k, str) and k.strip():
                    strings.add(k)
        for english in address_en.values():
            if isinstance(english, str) and english.strip():
                strings.add(english)
        for english in OPTION_TRANSLATIONS.get("en", {}).values():
            if isinstance(english, str) and english.strip():
                strings.add(english)

        self.stdout.write(f"Collected {len(strings)} unique English enum string(s).")

        # Translate missing strings per target.
        for tgt in targets:
            section_key = f"_en_{tgt}"
            bucket = cache.setdefault(section_key, {})
            missing = sorted(s for s in strings if s not in bucket)
            if missing:
                self.stdout.write(f"Translating {len(missing)} → {tgt}")
                self._translate_batched(missing, tgt, api_key, bucket)
                self._save_cache(cache)
            else:
                self.stdout.write(f"Enum cache already complete for {tgt}")

        # Build the output file content.
        lines = [
            "# Auto-generated by `python manage.py translate_enums`.",
            "# Do not edit by hand — re-run the command to refresh.",
            "",
        ]

        def _write_dict(var_name: str, mapping: dict) -> None:
            lines.append(f"{var_name} = {pformat(mapping, width=100, sort_dicts=True)}")
            lines.append("")

        for tgt in targets:
            bucket = cache[f"_en_{tgt}"]

            def _tr(v):
                return bucket.get(v, v) if isinstance(v, str) else v

            _write_dict(
                f"colors_dict_{tgt}",
                {k.lower(): _tr(k) for k in colors_dict if isinstance(k, str) and k.strip()},
            )
            _write_dict(
                f"fuel_types_dict_{tgt}",
                {k.lower(): _tr(k) for k in fuel_types_dict if isinstance(k, str) and k.strip()},
            )
            _write_dict(
                f"transmission_types_dict_{tgt}",
                {k.lower(): _tr(k) for k in transmission_types_dict if isinstance(k, str) and k.strip()},
            )
            _write_dict(
                f"body_types_dict_{tgt}",
                {k.lower(): _tr(k) for k in body_types_dict if isinstance(k, str) and k.strip()},
            )
            _write_dict(
                f"car_models_dict_{tgt}",
                {k.lower(): _tr(k) for k in car_models_dict if isinstance(k, str) and k.strip()},
            )
            _write_dict(
                f"address_{tgt}",
                {kor: _tr(english) for kor, english in address_en.items()},
            )
            _write_dict(
                f"options_dict_{tgt}",
                {code: _tr(english) for code, english in OPTION_TRANSLATIONS.get("en", {}).items()},
            )

        content = "\n".join(lines) + "\n"
        if opts["dry_run"]:
            self.stdout.write(f"[dry-run] would write {OUTPUT_FILE} ({len(content)} bytes)")
        else:
            OUTPUT_FILE.write_text(content, encoding="utf-8")
            self.stdout.write(self.style.SUCCESS(
                f"wrote {OUTPUT_FILE.relative_to(settings.BASE_DIR)}"
            ))

    # ─────── helpers ───────

    def _translate_batched(self, strings, target, api_key, bucket):
        for i in range(0, len(strings), BATCH_SIZE):
            chunk = strings[i : i + BATCH_SIZE]
            resp = requests.post(
                GT_URL,
                params={"key": api_key},
                data={"q": chunk, "source": "en", "target": target, "format": "text"},
                timeout=30,
            )
            if resp.status_code != 200:
                raise CommandError(
                    f"Google Translate API error {resp.status_code}: {resp.text[:500]}"
                )
            translations = resp.json()["data"]["translations"]
            for src, entry in zip(chunk, translations):
                bucket[src] = html.unescape(entry["translatedText"])

    def _load_cache(self) -> dict:
        if not CACHE_FILE.exists():
            return {}
        try:
            return json.loads(CACHE_FILE.read_text(encoding="utf-8"))
        except json.JSONDecodeError:
            return {}

    def _save_cache(self, cache: dict) -> None:
        CACHE_FILE.write_text(
            json.dumps(cache, ensure_ascii=False, indent=2, sort_keys=True),
            encoding="utf-8",
        )
