# Generated by Django 6.0.2 on 2026-02-13 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="SiteCar",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200, verbose_name="العنوان")),
                (
                    "description",
                    models.TextField(blank=True, null=True, verbose_name="الوصف"),
                ),
                (
                    "image",
                    models.URLField(
                        blank=True,
                        max_length=500,
                        null=True,
                        verbose_name="صورة رئيسية",
                    ),
                ),
                (
                    "images",
                    models.JSONField(blank=True, null=True, verbose_name="صور إضافية"),
                ),
                (
                    "manufacturer",
                    models.CharField(max_length=100, verbose_name="الشركة المصنعة"),
                ),
                ("model", models.CharField(max_length=100, verbose_name="الموديل")),
                ("year", models.IntegerField(verbose_name="سنة الصنع")),
                (
                    "color",
                    models.CharField(
                        blank=True, max_length=100, null=True, verbose_name="اللون"
                    ),
                ),
                (
                    "mileage",
                    models.BigIntegerField(default=0, verbose_name="المسافة المقطوعة"),
                ),
                ("price", models.BigIntegerField(verbose_name="السعر")),
                (
                    "transmission",
                    models.CharField(
                        blank=True,
                        max_length=100,
                        null=True,
                        verbose_name="ناقل الحركة",
                    ),
                ),
                (
                    "fuel",
                    models.CharField(
                        blank=True, max_length=100, null=True, verbose_name="الوقود"
                    ),
                ),
                (
                    "body_type",
                    models.CharField(
                        blank=True, max_length=100, null=True, verbose_name="نوع الهيكل"
                    ),
                ),
                (
                    "engine",
                    models.CharField(
                        blank=True, max_length=100, null=True, verbose_name="المحرك"
                    ),
                ),
                (
                    "drive_wheel",
                    models.CharField(
                        blank=True, max_length=100, null=True, verbose_name="نظام الدفع"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("available", "متاح"),
                            ("sold", "تم البيع"),
                            ("pending", "قيد الانتظار"),
                        ],
                        default="available",
                        max_length=20,
                        verbose_name="الحالة",
                    ),
                ),
                (
                    "is_featured",
                    models.BooleanField(default=False, verbose_name="مميزة"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "سيارة الموقع",
                "verbose_name_plural": "سيارات الموقع",
                "ordering": ["-created_at"],
            },
        ),
    ]
