# Generated by Django 6.0.2 on 2026-02-13 12:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cars", "0002_remove_order_car_remove_order_port_remove_order_user_and_more"),
        ("site_cars", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="SiteOrder",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "offer_price",
                    models.DecimalField(
                        decimal_places=2, max_digits=12, verbose_name="السعر المعروض"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "قيد المراجعة"),
                            ("accepted", "مقبول"),
                            ("rejected", "مرفوض"),
                            ("completed", "مكتمل"),
                        ],
                        default="pending",
                        max_length=20,
                        verbose_name="الحالة",
                    ),
                ),
                ("notes", models.TextField(blank=True, verbose_name="ملاحظات العميل")),
                (
                    "admin_notes",
                    models.TextField(blank=True, verbose_name="ملاحظات الإدارة"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "car",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="cars.apicar",
                        verbose_name="السيارة",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="site_orders",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "طلب",
                "verbose_name_plural": "الطلبات",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="SiteBill",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "price",
                    models.DecimalField(
                        decimal_places=2, max_digits=12, verbose_name="المبلغ"
                    ),
                ),
                (
                    "receipt_number",
                    models.CharField(
                        blank=True,
                        max_length=100,
                        null=True,
                        verbose_name="رقم الإيصال",
                    ),
                ),
                (
                    "description",
                    models.CharField(blank=True, max_length=255, verbose_name="الوصف"),
                ),
                ("date", models.DateField(verbose_name="التاريخ")),
                ("is_paid", models.BooleanField(default=False, verbose_name="مدفوعة")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "order",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="bills",
                        to="site_cars.siteorder",
                        verbose_name="الطلب",
                    ),
                ),
            ],
            options={
                "verbose_name": "فاتورة",
                "verbose_name_plural": "الفواتير",
                "ordering": ["-date"],
            },
        ),
        migrations.CreateModel(
            name="SiteQuestion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("question", models.TextField(verbose_name="السؤال")),
                (
                    "answer",
                    models.TextField(blank=True, null=True, verbose_name="الإجابة"),
                ),
                (
                    "is_answered",
                    models.BooleanField(default=False, verbose_name="تمت الإجابة"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "car",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="cars.apicar",
                        verbose_name="السيارة",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="site_questions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "سؤال",
                "verbose_name_plural": "الأسئلة",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="SiteSoldCar",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "sale_price",
                    models.DecimalField(
                        decimal_places=2, max_digits=12, verbose_name="سعر البيع"
                    ),
                ),
                (
                    "original_price",
                    models.BigIntegerField(
                        blank=True, null=True, verbose_name="السعر الأصلي"
                    ),
                ),
                (
                    "sold_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="تاريخ البيع"),
                ),
                ("notes", models.TextField(blank=True, verbose_name="ملاحظات")),
                (
                    "buyer",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="purchased_cars",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="المشتري",
                    ),
                ),
                (
                    "car",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="cars.apicar",
                        verbose_name="السيارة",
                    ),
                ),
            ],
            options={
                "verbose_name": "سيارة مباعة",
                "verbose_name_plural": "السيارات المباعة",
                "ordering": ["-sold_at"],
            },
        ),
        migrations.CreateModel(
            name="SiteRating",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("rating", models.IntegerField(verbose_name="التقييم")),
                ("comment", models.TextField(blank=True, verbose_name="التعليق")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "car",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="cars.apicar",
                        verbose_name="السيارة",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="site_ratings",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "تقييم",
                "verbose_name_plural": "التقييمات",
                "ordering": ["-created_at"],
                "unique_together": {("user", "car")},
            },
        ),
    ]
