# Generated by Django 6.0.2 on 2026-02-13 12:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("site_cars", "0002_siteorder_sitebill_sitequestion_sitesoldcar_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="sitecar",
            name="images",
        ),
        migrations.AlterField(
            model_name="sitecar",
            name="image",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to="site_cars/",
                verbose_name="صورة رئيسية",
            ),
        ),
        migrations.CreateModel(
            name="SiteCarImage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "image",
                    models.ImageField(upload_to="site_cars/", verbose_name="الصورة"),
                ),
                (
                    "caption",
                    models.CharField(blank=True, max_length=200, verbose_name="وصف"),
                ),
                (
                    "order",
                    models.PositiveIntegerField(default=0, verbose_name="الترتيب"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "car",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="gallery",
                        to="site_cars.sitecar",
                        verbose_name="السيارة",
                    ),
                ),
            ],
            options={
                "verbose_name": "صورة",
                "verbose_name_plural": "صور السيارة",
                "ordering": ["order", "created_at"],
            },
        ),
    ]
