# Generated by Django 6.0.2 on 2026-02-13 13:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("site_cars", "0003_remove_sitecar_images_alter_sitecar_image_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="SiteEmailLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "recipient_email",
                    models.EmailField(max_length=254, verbose_name="البريد الإلكتروني"),
                ),
                ("subject", models.CharField(max_length=255, verbose_name="الموضوع")),
                ("body", models.TextField(verbose_name="المحتوى")),
                (
                    "email_type",
                    models.CharField(
                        choices=[
                            ("order_placed", "طلب جديد"),
                            ("order_status", "تحديث حالة الطلب"),
                            ("welcome", "ترحيب"),
                            ("custom", "رسالة مخصصة"),
                            ("broadcast", "رسالة جماعية"),
                        ],
                        default="custom",
                        max_length=20,
                        verbose_name="النوع",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("sent", "تم الإرسال"),
                            ("failed", "فشل"),
                            ("pending", "قيد الإرسال"),
                        ],
                        default="pending",
                        max_length=10,
                        verbose_name="الحالة",
                    ),
                ),
                (
                    "error_message",
                    models.TextField(blank=True, verbose_name="رسالة الخطأ"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "recipient_user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="المستخدم",
                    ),
                ),
            ],
            options={
                "verbose_name": "سجل بريد",
                "verbose_name_plural": "سجلات البريد",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="SiteMessage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("subject", models.CharField(max_length=255, verbose_name="الموضوع")),
                ("body", models.TextField(verbose_name="الرسالة")),
                ("is_read", models.BooleanField(default=False, verbose_name="مقروءة")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "parent",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="replies",
                        to="site_cars.sitemessage",
                        verbose_name="رد على",
                    ),
                ),
                (
                    "recipient",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="received_messages",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="المستلم",
                    ),
                ),
                (
                    "sender",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sent_messages",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="المرسل",
                    ),
                ),
            ],
            options={
                "verbose_name": "رسالة",
                "verbose_name_plural": "الرسائل",
                "ordering": ["-created_at"],
            },
        ),
    ]
