# Generated by Django 6.0.2 on 2026-02-16 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("site_cars", "0004_siteemaillog_sitemessage"),
    ]

    operations = [
        migrations.AddField(
            model_name="siterating",
            name="is_approved",
            field=models.BooleanField(default=False, verbose_name="موافق عليه"),
        ),
    ]
