# Generated by Django 6.0.2 on 2026-04-22 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_cars', '0007_sitecar_external_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitecar',
            name='auction_end',
            field=models.DateTimeField(blank=True, null=True, verbose_name='نهاية المزاد'),
        ),
        migrations.AddField(
            model_name='sitecar',
            name='claims_count',
            field=models.PositiveSmallIntegerField(db_index=True, default=0, help_text='إجمالي مطالبات التأمين (الذاتية + الطرف الآخر).', verbose_name='عدد الحوادث'),
        ),
        migrations.AddField(
            model_name='sitecar',
            name='engine_cc',
            field=models.IntegerField(blank=True, null=True, verbose_name='حجم المحرك (سي سي)'),
        ),
        migrations.AddField(
            model_name='sitecar',
            name='insurance_history',
            field=models.JSONField(blank=True, help_text='البيانات الخام: plate_changes / owner_changes / own_damage / opposing_damage.', null=True, verbose_name='سجل التأمين'),
        ),
        migrations.AddField(
            model_name='sitecar',
            name='location',
            field=models.CharField(blank=True, default='', max_length=200, verbose_name='موقع التخزين'),
        ),
        migrations.AddField(
            model_name='sitecar',
            name='month',
            field=models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='شهر الصنع'),
        ),
        migrations.AddField(
            model_name='sitecar',
            name='registration_no',
            field=models.CharField(blank=True, db_index=True, default='', max_length=50, verbose_name='رقم التسجيل'),
        ),
        migrations.AddField(
            model_name='sitecar',
            name='source_status',
            field=models.CharField(blank=True, db_index=True, default='', help_text='رمز الحالة الأصلي من المصدر (مثال: 폐차 / 구제 / 부품).', max_length=20, verbose_name='حالة المصدر'),
        ),
        migrations.AddField(
            model_name='sitecar',
            name='source_url',
            field=models.URLField(blank=True, default='', max_length=500, verbose_name='رابط الإعلان المصدر'),
        ),
        migrations.AddField(
            model_name='sitecar',
            name='trim',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='الطراز'),
        ),
    ]
