# Generated by Django 6.0.2 on 2026-04-23 19:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_cars', '0008_sitecar_auction_end_sitecar_claims_count_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitebill',
            name='buyer_address',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='عنوان المشتري'),
        ),
        migrations.AddField(
            model_name='sitebill',
            name='buyer_id_number',
            field=models.CharField(blank=True, default='', max_length=50, verbose_name='رقم الهوية'),
        ),
        migrations.AddField(
            model_name='sitebill',
            name='buyer_name',
            field=models.CharField(blank=True, default='', max_length=200, verbose_name='اسم المشتري'),
        ),
        migrations.AddField(
            model_name='sitebill',
            name='buyer_phone',
            field=models.CharField(blank=True, default='', max_length=50, verbose_name='جوال المشتري'),
        ),
        migrations.AddField(
            model_name='sitebill',
            name='site_car',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bills', to='site_cars.sitecar', verbose_name='السيارة'),
        ),
        migrations.AlterField(
            model_name='sitebill',
            name='order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bills', to='site_cars.siteorder', verbose_name='الطلب'),
        ),
        migrations.AlterField(
            model_name='sitebill',
            name='receipt_number',
            field=models.CharField(blank=True, db_index=True, max_length=100, null=True, verbose_name='رقم الإيصال'),
        ),
    ]
