# Generated by Django 6.0.2 on 2026-04-23 19:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_cars', '0009_invoice_fields'),
    ]

    operations = [
        migrations.CreateModel(
            name='SiteShipment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('preparing', 'قيد التجهيز'), ('loaded', 'تم التحميل'), ('in_transit', 'قيد الشحن'), ('arrived', 'وصلت الميناء'), ('delivered', 'تم التسليم'), ('cancelled', 'ملغي')], db_index=True, default='preparing', max_length=20, verbose_name='الحالة')),
                ('shipping_company', models.CharField(blank=True, default='', max_length=150, verbose_name='شركة الشحن')),
                ('vessel_name', models.CharField(blank=True, default='', max_length=150, verbose_name='اسم السفينة')),
                ('container_number', models.CharField(blank=True, db_index=True, default='', max_length=50, verbose_name='رقم الحاوية')),
                ('bill_of_lading', models.CharField(blank=True, db_index=True, default='', max_length=100, verbose_name='بوليصة الشحن')),
                ('origin_port', models.CharField(blank=True, default='', max_length=150, verbose_name='ميناء الشحن')),
                ('destination_port', models.CharField(blank=True, default='', max_length=150, verbose_name='ميناء الوصول')),
                ('destination_country', models.CharField(blank=True, default='', max_length=100, verbose_name='دولة الوصول')),
                ('etd', models.DateField(blank=True, null=True, verbose_name='تاريخ المغادرة المتوقع')),
                ('eta', models.DateField(blank=True, null=True, verbose_name='تاريخ الوصول المتوقع')),
                ('delivered_at', models.DateField(blank=True, null=True, verbose_name='تاريخ التسليم')),
                ('shipping_cost', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='تكلفة الشحن')),
                ('tracking_url', models.URLField(blank=True, default='', max_length=500, verbose_name='رابط التتبع')),
                ('notes', models.TextField(blank=True, default='', verbose_name='ملاحظات')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('bill', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='shipment', to='site_cars.sitebill', verbose_name='الفاتورة')),
            ],
            options={
                'verbose_name': 'شحنة',
                'verbose_name_plural': 'الشحنات',
                'ordering': ['-created_at'],
            },
        ),
    ]
