# Generated by Django 6.0.2 on 2026-05-07 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_cars', '0010_siteshipment'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitecar',
            name='plate_number',
            field=models.CharField(blank=True, db_index=True, max_length=32, null=True, verbose_name='رقم اللوحة'),
        ),
        migrations.AddField(
            model_name='sitecar',
            name='vin',
            field=models.CharField(blank=True, db_index=True, max_length=64, null=True, verbose_name='رقم الشاسيه (VIN)'),
        ),
    ]
