# Generated by Django 6.0.2 on 2026-06-03 14:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0028_add_unique_constraints'),
        ('site_cars', '0011_sitecar_plate_number_sitecar_vin'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='siterating',
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name='siterating',
            name='car',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='cars.apicar', verbose_name='السيارة'),
        ),
        migrations.AddConstraint(
            model_name='siterating',
            constraint=models.UniqueConstraint(condition=models.Q(('car__isnull', True)), fields=('user',), name='unique_site_rating_per_user'),
        ),
        migrations.AddConstraint(
            model_name='siterating',
            constraint=models.UniqueConstraint(fields=('user', 'car'), name='unique_car_rating_per_user'),
        ),
    ]
