# Generated by Django 6.0.2 on 2026-06-03 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_cars', '0012_alter_siterating_unique_together_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SiteFaq',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.TextField(verbose_name='السؤال')),
                ('answer', models.TextField(blank=True, verbose_name='الإجابة')),
                ('is_published', models.BooleanField(default=False, verbose_name='منشور')),
                ('is_user_submitted', models.BooleanField(default=False, verbose_name='من زائر')),
                ('submitter_name', models.CharField(blank=True, max_length=120, verbose_name='اسم المُرسِل')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='الترتيب')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'سؤال شائع',
                'verbose_name_plural': 'الأسئلة الشائعة',
                'ordering': ['order', '-created_at'],
            },
        ),
    ]
