# Generated by Django 6.0.2 on 2026-06-03 14:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_cars', '0013_sitefaq'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='sitebill',
            name='buyer_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='purchase_bills', to=settings.AUTH_USER_MODEL, verbose_name='حساب العميل'),
        ),
        migrations.CreateModel(
            name='SiteBillItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, default='', max_length=255, verbose_name='البيان')),
                ('price', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='السعر')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('bill', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='site_cars.sitebill', verbose_name='الفاتورة')),
                ('site_car', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bill_items', to='site_cars.sitecar', verbose_name='السيارة')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
    ]
