# Generated by Django 6.0.2 on 2026-06-10 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_cars', '0015_backfill_bill_items'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitecar',
            name='currency',
            field=models.CharField(choices=[('KRW', '₩ KRW'), ('SAR', '﷼ SAR'), ('USD', '$ USD'), ('AED', 'د.إ AED'), ('EUR', '€ EUR')], default='KRW', max_length=3, verbose_name='عملة السعر'),
        ),
    ]
