# Generated by Django 6.0.2 on 2026-06-10 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_cars', '0016_sitecar_currency'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitecar',
            name='inspection_video',
            field=models.FileField(blank=True, null=True, upload_to='site_cars/videos/', verbose_name='فيديو الفحص'),
        ),
        migrations.AddField(
            model_name='sitecar',
            name='inspection_video_url',
            field=models.URLField(blank=True, null=True, verbose_name='رابط فيديو الفحص (يوتيوب/رابط مباشر)'),
        ),
    ]
