# Generated by Django 6.0.2 on 2026-06-16 18:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_cars', '0017_sitecar_inspection_video_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='siterating',
            name='name',
            field=models.CharField(blank=True, default='', max_length=120, verbose_name='الاسم'),
        ),
        migrations.AlterField(
            model_name='siterating',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='site_ratings', to=settings.AUTH_USER_MODEL),
        ),
    ]
