# Generated by Django 6.0.2 on 2026-06-24 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_cars', '0018_siterating_name_alter_siterating_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='SharedCollection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(db_index=True, editable=False, max_length=16, unique=True)),
                ('title', models.CharField(blank=True, default='', max_length=120, verbose_name='عنوان')),
                ('car_refs', models.JSONField(default=list, verbose_name='السيارات')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'مجموعة مشاركة',
                'verbose_name_plural': 'مجموعات المشاركة',
                'ordering': ['-created_at'],
            },
        ),
    ]
