# Generated by Django 6.0.2 on 2026-07-02 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_cars', '0020_userprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitecarimage',
            name='image_url',
            field=models.URLField(blank=True, default='', max_length=500, verbose_name='رابط الصورة'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='identity_number',
            field=models.CharField(blank=True, db_index=True, default='', max_length=20, verbose_name='رقم الهوية'),
        ),
        migrations.AlterField(
            model_name='sitecarimage',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='site_cars/', verbose_name='الصورة'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='phone',
            field=models.CharField(blank=True, db_index=True, default='', max_length=30, verbose_name='رقم الجوال'),
        ),
    ]
