# Generated by Django 6.0.2 on 2026-07-10 14:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_cars', '0021_sitecarimage_image_url_userprofile_identity_number_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SiteReceipt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('receipt_number', models.CharField(blank=True, db_index=True, max_length=100, null=True, verbose_name='رقم السند')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='المبلغ المستلم')),
                ('method', models.CharField(choices=[('transfer', 'حوالة بنكية'), ('cash', 'نقداً'), ('card', 'شبكة / بطاقة'), ('cheque', 'شيك')], default='transfer', max_length=12, verbose_name='طريقة الدفع')),
                ('purpose', models.CharField(choices=[('deposit', 'عربون حجز السيارة'), ('partial', 'دفعة من قيمة السيارة'), ('final', 'سداد باقي قيمة السيارة'), ('other', 'أخرى')], default='deposit', max_length=12, verbose_name='الغرض')),
                ('note', models.CharField(blank=True, default='', max_length=255, verbose_name='ملاحظة')),
                ('received_by', models.CharField(blank=True, default='', max_length=120, verbose_name='اسم المستلم')),
                ('date', models.DateField(verbose_name='التاريخ')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('bill', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='receipts', to='site_cars.sitebill', verbose_name='الفاتورة')),
            ],
            options={
                'verbose_name': 'سند قبض',
                'verbose_name_plural': 'سندات القبض',
                'ordering': ['-date', '-id'],
            },
        ),
    ]
