# Generated by Django 6.0.2 on 2026-07-15 10:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_cars', '0022_sitereceipt'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='StaffAccess',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('can_cars', models.BooleanField(default=False, verbose_name='السيارات والمخزون')),
                ('can_sales', models.BooleanField(default=False, verbose_name='الفواتير والإيصالات')),
                ('can_orders', models.BooleanField(default=False, verbose_name='طلبات العملاء')),
                ('can_reviews', models.BooleanField(default=False, verbose_name='التقييمات والأسئلة')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='staff_accounts_created', to=settings.AUTH_USER_MODEL)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='staff_access', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'صلاحيات موظف',
                'verbose_name_plural': 'صلاحيات الموظفين',
            },
        ),
    ]
