# Generated by Django 6.0.2 on 2026-07-15 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_cars', '0024_grant_existing_staff_full_access'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sitecar',
            name='auction_end',
            field=models.DateTimeField(blank=True, db_index=True, null=True, verbose_name='نهاية المزاد'),
        ),
    ]
