# Generated by Django 6.0.2 on 2026-07-20 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_cars', '0025_alter_sitecar_auction_end'),
    ]

    operations = [
        migrations.AddField(
            model_name='sharedcollection',
            name='options',
            field=models.JSONField(blank=True, default=dict, verbose_name='خيارات العرض'),
        ),
    ]
