# Generated by Django 6.0.2 on 2026-07-21 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_cars', '0026_sharedcollection_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitebillitem',
            name='vin',
            field=models.CharField(blank=True, default='', max_length=64, verbose_name='رقم الهيكل (VIN)'),
        ),
    ]
