# Generated by Django 6.0.2 on 2026-02-13 12:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("cars", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="order",
            name="car",
        ),
        migrations.RemoveField(
            model_name="order",
            name="port",
        ),
        migrations.RemoveField(
            model_name="order",
            name="user",
        ),
        migrations.RemoveField(
            model_name="question",
            name="user",
        ),
        migrations.RemoveField(
            model_name="rating",
            name="car",
        ),
        migrations.RemoveField(
            model_name="rating",
            name="user",
        ),
        migrations.DeleteModel(
            name="Bill",
        ),
        migrations.DeleteModel(
            name="Order",
        ),
        migrations.DeleteModel(
            name="Question",
        ),
        migrations.DeleteModel(
            name="Rating",
        ),
    ]
