# Generated by Django 6.0.2 on 2026-02-13 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cars", "0002_remove_order_car_remove_order_port_remove_order_user_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="apicar",
            name="auction_date",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
