# Generated by Django 6.0.2 on 2026-02-13 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cars", "0003_alter_apicar_auction_date"),
    ]

    operations = [
        migrations.AddField(
            model_name="manufacturer",
            name="name_ar",
            field=models.CharField(
                blank=True, max_length=100, null=True, verbose_name="الاسم بالعربي"
            ),
        ),
    ]
