# Generated by Django 6.0.2 on 2026-02-14 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cars", "0004_manufacturer_name_ar"),
    ]

    operations = [
        migrations.AddField(
            model_name="bodytype",
            name="name_ar",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
