# Generated by Django 6.0.2 on 2026-02-14 13:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("cars", "0006_wishlist"),
    ]

    operations = [
        # Drop the old foreign key constraint that's causing the issue
        migrations.RunSQL(
            "ALTER TABLE cars_wishlist DROP CONSTRAINT IF EXISTS cars_wishlist_user_id_a25befc2_fk_auth_user_id",
            migrations.RunSQL.noop,
        ),
    ]
