# Generated by Django 6.0.2 on 2026-02-17 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cars", "0008_post_postcomment_postimage_postlike"),
    ]

    operations = [
        migrations.AddField(
            model_name="post",
            name="video_url",
            field=models.URLField(
                blank=True,
                help_text="رابط فيديو من YouTube أو Vimeo أو غيرها",
                null=True,
                verbose_name="رابط الفيديو",
            ),
        ),
    ]
