# Generated by Django 6.0.2 on 2026-02-18 11:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("cars", "0009_post_video_url"),
    ]

    operations = [
        migrations.RenameField(
            model_name="apicar",
            old_name="conition",
            new_name="condition",
        ),
    ]
