# Generated by Django 6.0.2 on 2026-02-18 12:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cars", "0010_rename_conition_apicar_condition"),
        ("tenants", "0009_tenant_hero_image"),
    ]

    operations = [
        migrations.AddField(
            model_name="post",
            name="tenant",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="tenants.tenant",
                verbose_name="الموقع",
            ),
        ),
    ]
