# Generated by Django 6.0.2 on 2026-02-18 14:04

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cars", "0011_add_tenant_to_post"),
        ("tenants", "0009_tenant_hero_image"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="apicar",
            name="auction_date",
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name="apicar",
            name="car_id",
            field=models.CharField(db_index=True, max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name="apicar",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name="apicar",
            name="fuel",
            field=models.CharField(
                blank=True, db_index=True, max_length=100, null=True
            ),
        ),
        migrations.AlterField(
            model_name="apicar",
            name="is_leasing",
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AlterField(
            model_name="apicar",
            name="is_luxury",
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AlterField(
            model_name="apicar",
            name="is_special",
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AlterField(
            model_name="apicar",
            name="mileage",
            field=models.BigIntegerField(db_index=True),
        ),
        migrations.AlterField(
            model_name="apicar",
            name="price",
            field=models.BigIntegerField(db_index=True),
        ),
        migrations.AlterField(
            model_name="apicar",
            name="status",
            field=models.CharField(
                choices=[
                    ("available", "متاح"),
                    ("sold", "تم البيع"),
                    ("pending", "قيد الانتظار"),
                ],
                db_index=True,
                default="available",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="apicar",
            name="title",
            field=models.CharField(db_index=True, max_length=100),
        ),
        migrations.AlterField(
            model_name="apicar",
            name="transmission",
            field=models.CharField(
                blank=True, db_index=True, max_length=100, null=True
            ),
        ),
        migrations.AlterField(
            model_name="apicar",
            name="year",
            field=models.IntegerField(db_index=True),
        ),
        migrations.AlterField(
            model_name="post",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True, db_index=True, verbose_name="تاريخ الإنشاء"
            ),
        ),
        migrations.AlterField(
            model_name="post",
            name="is_published",
            field=models.BooleanField(
                db_index=True, default=True, verbose_name="منشور"
            ),
        ),
        migrations.AlterField(
            model_name="post",
            name="title",
            field=models.CharField(
                db_index=True, max_length=200, verbose_name="العنوان"
            ),
        ),
        migrations.AddIndex(
            model_name="apicar",
            index=models.Index(
                fields=["-created_at", "status"], name="cars_apicar_created_b94a35_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="apicar",
            index=models.Index(
                fields=["category", "-auction_date"],
                name="cars_apicar_categor_11335f_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="apicar",
            index=models.Index(
                fields=["manufacturer", "year"], name="cars_apicar_manufac_175a5f_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="apicar",
            index=models.Index(
                fields=["price", "mileage"], name="cars_apicar_price_c6243f_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="post",
            index=models.Index(
                fields=["tenant", "-created_at"], name="cars_post_tenant__ef3712_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="post",
            index=models.Index(
                fields=["is_published", "-created_at"],
                name="cars_post_is_publ_c74899_idx",
            ),
        ),
    ]
