# Generated by Django 6.0.2 on 2026-02-18 18:47

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cars", "0012_add_performance_indexes"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="wishlist",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AddIndex(
            model_name="wishlist",
            index=models.Index(
                fields=["user", "created_at"], name="cars_wishli_user_id_477742_idx"
            ),
        ),
    ]
