# Generated by Django 6.0.2 on 2026-02-20 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cars", "0013_wishlist_performance_indexes"),
    ]

    operations = [
        migrations.AddField(
            model_name="apicar",
            name="slug",
            field=models.SlugField(blank=True, max_length=200, null=True, unique=True),
        ),
    ]
