# Generated by Django 6.0.2 on 2026-02-21 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cars", "0014_add_slug_to_apicar"),
    ]

    operations = [
        migrations.AddField(
            model_name="apicar",
            name="entry",
            field=models.CharField(
                blank=True, db_index=True, max_length=100, null=True
            ),
        ),
    ]
