# Generated by Django 6.0.2 on 2026-03-03 22:07

from django.db import migrations, models


class Migration(migrations.Migration):
    """
    Add two partial/composite indexes to speed up the hot query path:
      .exclude(category__name='auction', auction_date__lt=now)

    Index 1: (category_id, auction_date) — covers the joint filter on the FK
             + date column used in almost every ApiCar query.
    Index 2: (category_id, created_at DESC) — covers the ORDER BY -created_at
             + category filter used by latest_cars / latest_auctions.
    """

    dependencies = [
        ("cars", "0015_apicar_entry"),
    ]

    operations = [
        migrations.AddIndex(
            model_name="apicar",
            index=models.Index(
                fields=["category", "auction_date"],
                name="cars_apicar_cat_auc_date_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="apicar",
            index=models.Index(
                fields=["category", "-created_at"],
                name="cars_apicar_cat_created_idx",
            ),
        ),
    ]
