# Generated by Django 6.0.2 on 2026-03-06 23:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cars", "0019_add_static_filter_covering_index"),
    ]

    operations = [
        migrations.CreateModel(
            name="CarSeatCount",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.RemoveIndex(
            model_name="apicar",
            name="cars_apicar_cat_auc_date_idx",
        ),
        migrations.RemoveIndex(
            model_name="apicar",
            name="cars_apicar_cat_created_idx",
        ),
    ]
