# Generated by Django 6.0.2 on 2026-03-24 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cars", "0020_carseatcount_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="carmodel",
            name="name_ar",
            field=models.CharField(
                blank=True, max_length=100, null=True, verbose_name="الاسم بالعربي"
            ),
        ),
    ]
