# Generated by Django 6.0.2 on 2026-03-24 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cars", "0022_pdfexport"),
    ]

    operations = [
        migrations.AddField(
            model_name="pdfexport",
            name="make_name",
            field=models.CharField(blank=True, max_length=200, verbose_name="الماركة"),
        ),
    ]
