# Generated by Django 6.0.2 on 2026-04-06 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0024_wishlist_session_based'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='wishlist',
            name='cars_wishli_user_id_477742_idx',
        ),
        migrations.AddIndex(
            model_name='wishlist',
            index=models.Index(fields=['session_key', 'created_at'], name='cars_wishli_session_ca8b49_idx'),
        ),
    ]
