# Generated by Django 6.0.2 on 2026-06-20 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0028_add_unique_constraints'),
    ]

    operations = [
        migrations.AddField(
            model_name='apicar',
            name='engine_group',
            field=models.CharField(blank=True, db_index=True, max_length=60, null=True),
        ),
        migrations.AddField(
            model_name='apicar',
            name='model_version',
            field=models.CharField(blank=True, db_index=True, max_length=120, null=True),
        ),
        migrations.AddField(
            model_name='apicar',
            name='model_year_range',
            field=models.CharField(blank=True, db_index=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='apicar',
            name='trim_detail',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
