# Generated by Django 6.0.2 on 2026-06-21 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0029_apicar_engine_group_apicar_model_version_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='apicar',
            name='features',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='apicar',
            name='first_registration',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
        migrations.AddField(
            model_name='apicar',
            name='inspection_notes',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='apicar',
            name='usage_type',
            field=models.CharField(blank=True, db_index=True, default='', max_length=40),
        ),
    ]
