# Generated by Django 6.0.2 on 2026-06-22 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0030_apicar_features_apicar_first_registration_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='apicar',
            name='inspection_report_url',
            field=models.CharField(blank=True, default='', max_length=500),
        ),
    ]
