# Generated by Django 6.0.2 on 2026-07-17 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0036_dmg_replaced_generated_column'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ['tab_order', 'name']},
        ),
        migrations.AddField(
            model_name='category',
            name='is_market_tab',
            field=models.BooleanField(default=False, verbose_name='تبويب سوق مستقل'),
        ),
        migrations.AddField(
            model_name='category',
            name='label_ar',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='category',
            name='label_en',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='category',
            name='tab_order',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
