from django.urls import path
from . import views

urlpatterns = [
    path('dashboard/', views.dashboard, name='site_dashboard'),
    # Shareable car collections (staff builder + public view)
    path('dashboard/share/', views.share_builder, name='share_builder'),
    path('dashboard/share/search/', views.share_search, name='share_search'),
    path('dashboard/share/create/', views.share_create, name='share_create'),
    path('dashboard/share/<int:pk>/delete/', views.share_delete, name='share_delete'),
    path('c/<str:token>/', views.shared_collection, name='shared_collection'),
    path('share-cart/', views.cart_page, name='cart_page'),
    path('telegram/status/', views.telegram_status, name='telegram_status'),
    path('telegram/send/', views.telegram_send, name='telegram_send'),
    path('our-cars/', views.site_car_list, name='site_car_list'),
    path('our-cars/add/', views.site_car_add, name='site_car_add'),
    path('our-cars/<int:pk>/', views.site_car_detail, name='site_car_detail'),
    path('our-cars/<int:pk>/edit/', views.site_car_edit, name='site_car_edit'),
    path('our-cars/<int:pk>/delete/', views.site_car_delete, name='site_car_delete'),
    path('our-cars/<int:pk>/status/', views.site_car_change_status, name='site_car_change_status'),
    path('our-cars/<int:pk>/delete-image/<int:image_id>/', views.site_car_delete_image, name='site_car_delete_image'),
    path('track/<str:receipt_number>/', views.public_track, name='public_track'),
    path('our-cars/save/<int:api_car_id>/', views.save_public_car, name='save_public_car'),
    path('auctions/browse/', views.auction_browse, name='auction_browse'),
    path('our-cars/<int:pk>/invoice/new/', views.invoice_new, name='invoice_new'),
    path('our-cars/<int:pk>/invoice/<int:bill_pk>/', views.invoice_view, name='invoice_view'),
    path('our-cars/<int:pk>/invoice/<int:bill_pk>/contract/', views.contract_view, name='contract_view'),
    path('our-cars/<int:pk>/invoice/<int:bill_pk>/edit/', views.invoice_edit, name='invoice_edit'),
    path('our-cars/<int:pk>/invoice/<int:bill_pk>/shipment/', views.shipment_edit, name='shipment_edit'),
    path('sold-cars/', views.sold_cars, name='sold_cars'),
    path('order/<int:pk>/', views.place_order, name='place_order'),
    path('account/', views.account_view, name='account'),
    path('my-orders/', views.my_orders, name='my_orders'),
    path('my-orders/<int:pk>/', views.order_detail, name='order_detail'),
    path('rate/<int:pk>/', views.rate_car, name='rate_car'),
    path('rate-site/', views.rate_site, name='rate_site'),
    path('faq/', views.faq, name='faq'),
    path('faq/manage/', views.faq_manage, name='faq_manage'),
    path('rating/<int:pk>/approve/', views.approve_rating, name='approve_rating'),
    path('rating/<int:pk>/reject/', views.reject_rating, name='reject_rating'),
    path('inbox/', views.inbox, name='inbox'),
    path('inbox/<int:pk>/', views.message_detail, name='message_detail'),
    path('inbox/compose/', views.compose_message, name='compose_message'),
    path('send-email/', views.send_email_view, name='send_email'),
    path('upload-auction/', views.upload_auction_json, name='upload_auction_json'),
    path('upload-auction/delete-expired/', views.delete_expired_auctions, name='delete_expired_auctions'),
    path('dashboard/import-happycar/', views.import_happycar_view, name='import_happycar'),
    path('dashboard/damaged-cars/delete-unsold/', views.delete_unsold_damaged, name='delete_unsold_damaged'),
    path('dashboard/delete-auctions/', views.delete_auctions, name='delete_auctions'),
    path('staff/orders/', views.staff_orders, name='staff_orders'),
    path('staff/orders/<int:pk>/update/', views.staff_order_update, name='staff_order_update'),
    path('staff/ratings/', views.staff_ratings, name='staff_ratings'),
    path('staff/questions/', views.staff_questions, name='staff_questions'),
    path('staff/questions/<int:pk>/answer/', views.staff_question_answer, name='staff_question_answer'),
]
