"""
Django settings for cars_multi_site project.

Generated by 'django-admin startproject' using Django 5.2.5.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

import os
from pathlib import Path
import dj_database_url

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.environ.get("SECRET_KEY", "django-insecure-d!o0+huz$w^paapq#w6n3l-2r!ri)c7l(ju#%s)la@5j63-0ki")

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = os.environ.get("DEBUG", "True").lower() in ("true", "1", "yes")

_allowed_hosts_env = os.environ.get("ALLOWED_HOSTS", "")
ALLOWED_HOSTS = (
    [h.strip() for h in _allowed_hosts_env.split(",") if h.strip()]
    if _allowed_hosts_env
    else ["localhost", "127.0.0.1", ".localhost"]
)
# Always allow Railway domains
ALLOWED_HOSTS += [".up.railway.app", "web-production-91b20.up.railway.app"]
# Allow any custom domain added to the Domain table — django-tenants handles routing
ALLOWED_HOSTS += ["*"]

# Base URL used to build the ofleet webhook callback URL.
# Set this in your Railway env vars to your production domain,
# e.g. WEBHOOK_BASE_URL=https://ofleet0.yoursite.com
# If not set, the webhook URL is built from the incoming request (works in production,
# but NOT when running locally since ofleet can't reach 127.0.0.1).
WEBHOOK_BASE_URL = os.environ.get("WEBHOOK_BASE_URL", "")


# Application definition

SHARED_APPS = [
    "django_tenants",
    "tenants",
    "billing",
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    "django_htmx",
    "cars",
    "django.contrib.humanize",
    "tailwind",
    "theme",
]

TENANT_APPS = [
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    "site_cars",
]
TAILWIND_APP_NAME = "theme"


INSTALLED_APPS = list(SHARED_APPS) + [app for app in TENANT_APPS if app not in SHARED_APPS]

if DEBUG:
    INSTALLED_APPS += ["debug_toolbar"]

MIDDLEWARE = [
    "tenants.middleware.QueryStringGuardMiddleware",
    "django_tenants.middleware.main.TenantMainMiddleware",
    "tenants.middleware.BlockTenantAdminMiddleware",
    "tenants.middleware.TenantPublicSchemaMiddleware",
    "django.middleware.security.SecurityMiddleware",
    "whitenoise.middleware.WhiteNoiseMiddleware",
    "django.middleware.gzip.GZipMiddleware",         # ← compress HTML ~85%
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
    "django_htmx.middleware.HtmxMiddleware",

]

if DEBUG:
    # Insert after GZipMiddleware (index 7 = after gzip at index 6)
    MIDDLEWARE.insert(7, "debug_toolbar.middleware.DebugToolbarMiddleware")
    INTERNAL_IPS = ["127.0.0.1", "localhost"]

ROOT_URLCONF = "cars_multi_site.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [BASE_DIR / "templates"],
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
                "tenants.context_processors.tenant_branding",
            ],
            "loaders": [
                "tenants.template_loader.TenantThemeLoader",
                "django.template.loaders.filesystem.Loader",
                "django.template.loaders.app_directories.Loader",
            ],
        },
    },
]

WSGI_APPLICATION = "cars_multi_site.wsgi.application"


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

DATABASES = {
    "default": {
        "ENGINE": "django_tenants.postgresql_backend",
        "NAME": "cars_multi_site",
        "USER": "postgres",
        "PASSWORD": "postgres",
        "HOST": "localhost",
        "PORT": "5432",
        "CONN_MAX_AGE": 600,  # Keep connections alive for 10 minutes
        "CONN_HEALTH_CHECKS": True,  # Reuse healthy connections
        "OPTIONS": {
            "connect_timeout": 10,
            "options": "-c statement_timeout=30000",  # 30 second query timeout
        }
    }
}

# Override with DATABASE_URL if set (Heroku)
if os.environ.get("DATABASE_URL"):
    db_from_env = dj_database_url.config(
        conn_max_age=60,        # Reuse connections for up to 60s — saves 150-400ms SSL handshake per request
        ssl_require=True
    )
    db_from_env["ENGINE"] = "django_tenants.postgresql_backend"
    db_from_env["CONN_HEALTH_CHECKS"] = True   # Test connection before reuse — prevents stale-socket 500s
    db_from_env["OPTIONS"] = {
        "connect_timeout": 10,  # Web requests: fail fast if DB unreachable (release.sh handles longer waits)
        "options": "-c statement_timeout=25000",
    }
    DATABASES["default"] = db_from_env

DATABASE_ROUTERS = (
    "django_tenants.routers.TenantSyncRouter",
)

# Caching Configuration
_REDIS_URL = os.environ.get("REDIS_URL")

if _REDIS_URL:
    CACHES = {
        "default": {
            "BACKEND": "django_redis.cache.RedisCache",
            "LOCATION": _REDIS_URL,
            "OPTIONS": {
                "CLIENT_CLASS": "django_redis.client.DefaultClient",
                "CONNECTION_POOL_KWARGS": {
                    "max_connections": 5,
                },
                "SOCKET_CONNECT_TIMEOUT": 5,
                "SOCKET_TIMEOUT": 5,
                "IGNORE_EXCEPTIONS": True,  # Degrade gracefully if Redis is down
            },
            "KEY_PREFIX": "cars",
        }
    }
else:
    CACHES = {
        "default": {
            "BACKEND": "django.core.cache.backends.locmem.LocMemCache",
        }
    }

# Cache timeouts (in seconds)
CACHE_MIDDLEWARE_SECONDS = 300  # 5 minutes
CACHE_MIDDLEWARE_KEY_PREFIX = "cars_multi_site"


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = "en-us"

TIME_ZONE = "Asia/Riyadh"

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = "static/"
STATIC_ROOT = BASE_DIR / "staticfiles"
STATICFILES_DIRS = [
    BASE_DIR / "static",
]
WHITENOISE_MAX_AGE = 31536000  # 1 year — safe because WhiteNoise uses content-hash filenames

MEDIA_URL = "/media/"
MEDIA_ROOT = BASE_DIR / "media"

# File Upload Settings - Optimized for Heroku
# Maximum size for in-memory files (2.5MB)
FILE_UPLOAD_MAX_MEMORY_SIZE = 2621440

# Maximum size for POST data (100MB total)
DATA_UPLOAD_MAX_MEMORY_SIZE = 104857600

# Maximum number of files that can be uploaded at once
DATA_UPLOAD_MAX_NUMBER_FILES = 25

# Use temporary file storage for larger uploads
FILE_UPLOAD_HANDLERS = [
    'django.core.files.uploadhandler.MemoryFileUploadHandler',
    'django.core.files.uploadhandler.TemporaryFileUploadHandler',
]

# Timeout settings (important for Heroku)
# Note: Heroku has a 30-second request timeout limit
# For large uploads, consider using background tasks or chunked uploads

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"

TENANT_MODEL = "tenants.Tenant"
TENANT_DOMAIN_MODEL = "tenants.Domain"

# ── CSRF / HTTPS proxy (Railway + Cloudflare sit in front as HTTPS proxies) ──
# Tell Django to trust the X-Forwarded-Proto header set by the proxy
SECURE_PROXY_SSL_HEADER = ("HTTP_X_FORWARDED_PROTO", "https")

# Allow CSRF cookies from all tenant domains on both http and https.
# Using wildcards so any custom domain added via the Domain admin works automatically.
_CSRF_DOMAINS = os.environ.get("CSRF_TRUSTED_ORIGINS", "")
CSRF_TRUSTED_ORIGINS = (
    [d.strip() for d in _CSRF_DOMAINS.split(",") if d.strip()]
    if _CSRF_DOMAINS
    else ["https://*", "http://*"]
)

LOGIN_URL = "login"
LOGIN_REDIRECT_URL = "home"
LOGOUT_REDIRECT_URL = "home"

EMAIL_BACKEND = "site_cars.email_backend.TenantEmailBackend"



# AWS S3 Settings
AWS_ACCESS_KEY_ID = os.environ.get('AWS_ACCESS_KEY_ID')
AWS_SECRET_ACCESS_KEY = os.environ.get('AWS_SECRET_ACCESS_KEY')
AWS_STORAGE_BUCKET_NAME = os.environ.get('AWS_STORAGE_BUCKET_NAME')
AWS_S3_REGION_NAME = os.environ.get('AWS_S3_REGION_NAME')

# AWS CloudFront Settings
AWS_S3_CUSTOM_DOMAIN = os.environ.get('CLOUDFRONT_DOMAIN', None)
AWS_S3_FILE_OVERWRITE = False

# Disable ACL since bucket has Object Ownership enabled
AWS_DEFAULT_ACL = None
AWS_BUCKET_ACL = None
AWS_S3_OBJECT_PARAMETERS = {
    'CacheControl': 'max-age=86400',
}

# Media files
if DEBUG:
    MEDIA_URL = '/media/'
    MEDIA_ROOT = BASE_DIR / 'media'
else:
    MEDIA_URL = f'https://{AWS_S3_CUSTOM_DOMAIN}/'
    MEDIA_ROOT = ''  # Media root is not used with S3

if not DEBUG:
    STORAGES = {
        "default": {
            "BACKEND": "storages.backends.s3boto3.S3Boto3Storage",
        },
        "staticfiles": {
            "BACKEND": "cars_multi_site.storage.RelaxedManifestStaticFilesStorage",
        }
    }
else:
    STORAGES = {
        "default": {
            "BACKEND": "django.core.files.storage.FileSystemStorage",
        },
        "staticfiles": {
            "BACKEND": "django.contrib.staticfiles.storage.StaticFilesStorage",
        }
    }

# ── ofleet PDF Export API ─────────────────────────────────────────────────
OFLEET_API_BASE  = os.environ.get("OFLEET_API_BASE",  "https://ofleet0.com")
OFLEET_USERNAME  = os.environ.get("OFLEET_USERNAME",  "")
OFLEET_PASSWORD  = os.environ.get("OFLEET_PASSWORD",  "")



R2_ACCOUNT_ID=os.environ.get("R2_ACCOUNT_ID", "")
R2_ACCESS_KEY_ID=os.environ.get("R2_ACCESS_KEY_ID", "")
R2_SECRET_ACCESS_KEY=os.environ.get("R2_SECRET_ACCESS_KEY", "")

# ── Stripe billing ────────────────────────────────────────────────────────
# Each non-public tenant must have an active subscription on this Price
# ($400/month) to access their site. Configure via env vars:
#   STRIPE_SECRET_KEY      — sk_live_... or sk_test_...
#   STRIPE_PUBLIC_KEY      — pk_live_... or pk_test_...
#   STRIPE_WEBHOOK_SECRET  — whsec_... (from the webhook endpoint dashboard)
#   STRIPE_PRICE_ID        — price_... for the recurring $400/mo product
STRIPE_SECRET_KEY     = os.environ.get("STRIPE_SECRET_KEY", "")
STRIPE_PUBLIC_KEY     = os.environ.get("STRIPE_PUBLIC_KEY", "")
STRIPE_WEBHOOK_SECRET = os.environ.get("STRIPE_WEBHOOK_SECRET", "")
STRIPE_PRICE_ID       = os.environ.get("STRIPE_PRICE_ID", "")