# Generated by Django 6.0.2 on 2026-05-09 13:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FooterColumn',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=80)),
                ('title_en', models.CharField(blank=True, max_length=80)),
                ('order', models.PositiveIntegerField(default=0)),
                ('is_visible', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='ListingConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('show_search', models.BooleanField(default=True)),
                ('show_manufacturer', models.BooleanField(default=True)),
                ('show_model', models.BooleanField(default=True)),
                ('show_year_range', models.BooleanField(default=True)),
                ('show_price_range', models.BooleanField(default=True)),
                ('show_fuel', models.BooleanField(default=True)),
                ('show_transmission', models.BooleanField(default=True)),
                ('show_body_type', models.BooleanField(default=True)),
                ('show_color', models.BooleanField(default=False)),
                ('show_mileage_range', models.BooleanField(default=False)),
                ('default_sort', models.CharField(choices=[('-created_at', 'Newest first'), ('created_at', 'Oldest first'), ('price', 'Price: low to high'), ('-price', 'Price: high to low'), ('-year', 'Year: newest')], default='-created_at', max_length=32)),
                ('page_size', models.PositiveIntegerField(default=24)),
            ],
            options={
                'verbose_name': 'Listing configuration',
                'verbose_name_plural': 'Listing configuration',
            },
        ),
        migrations.CreateModel(
            name='Page',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('home', 'Home'), ('about', 'About'), ('contact', 'Contact'), ('custom', 'Custom')], default='custom', max_length=16)),
                ('slug', models.SlugField(max_length=80, unique=True)),
                ('title', models.CharField(max_length=160)),
                ('title_en', models.CharField(blank=True, max_length=160)),
                ('meta_description', models.CharField(blank=True, max_length=300)),
                ('is_published', models.BooleanField(default=True)),
                ('show_in_nav', models.BooleanField(default=False)),
                ('nav_order', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['nav_order', 'title'],
                'constraints': [models.UniqueConstraint(condition=models.Q(('kind__in', ['home', 'about', 'contact'])), fields=('kind',), name='unique_singleton_page_kind')],
            },
        ),
        migrations.CreateModel(
            name='NavLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=80)),
                ('label_en', models.CharField(blank=True, max_length=80)),
                ('url', models.CharField(blank=True, help_text='Use this OR `page` — `url` wins if both are set.', max_length=300)),
                ('order', models.PositiveIntegerField(default=0)),
                ('is_visible', models.BooleanField(default=True)),
                ('open_in_new_tab', models.BooleanField(default=False)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='site_builder.navlink')),
                ('page', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='nav_links', to='site_builder.page')),
            ],
            options={
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='FooterLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=80)),
                ('label_en', models.CharField(blank=True, max_length=80)),
                ('url', models.CharField(blank=True, max_length=300)),
                ('order', models.PositiveIntegerField(default=0)),
                ('is_visible', models.BooleanField(default=True)),
                ('open_in_new_tab', models.BooleanField(default=False)),
                ('column', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='links', to='site_builder.footercolumn')),
                ('page', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='footer_links', to='site_builder.page')),
            ],
            options={
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='PageSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('hero', 'Hero'), ('text', 'Text'), ('html', 'Raw HTML'), ('featured_cars', 'Featured cars'), ('brand_strip', 'Brand strip'), ('gallery', 'Gallery'), ('cta', 'Call to action'), ('contact_form', 'Contact form')], max_length=32)),
                ('order', models.PositiveIntegerField(default=0)),
                ('is_visible', models.BooleanField(default=True)),
                ('title', models.CharField(blank=True, max_length=200)),
                ('title_en', models.CharField(blank=True, max_length=200)),
                ('subtitle', models.CharField(blank=True, max_length=300)),
                ('subtitle_en', models.CharField(blank=True, max_length=300)),
                ('body', models.TextField(blank=True, help_text='Plain text or HTML, depending on section type.')),
                ('image', models.ImageField(blank=True, null=True, upload_to='site_builder/sections/')),
                ('config', models.JSONField(blank=True, default=dict, help_text="Type-specific options. Examples: {'cta_label': 'Browse cars', 'cta_url': '/site_cars/'}, {'limit': 8, 'manufacturer': 'bmw'}, {'columns': 4}.")),
                ('page', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sections', to='site_builder.page')),
            ],
            options={
                'ordering': ['order', 'id'],
            },
        ),
    ]
