# Generated by Django 6.0.2 on 2026-07-16 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AssistantQuery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('schema_name', models.CharField(db_index=True, max_length=63)),
                ('username', models.CharField(blank=True, default='', max_length=150)),
                ('is_site_admin', models.BooleanField(default=False)),
                ('question', models.TextField()),
                ('answer', models.TextField(blank=True, default='')),
                ('status', models.CharField(choices=[('ok', 'answered'), ('error', 'error'), ('rate_limited', 'rate limited')], db_index=True, default='ok', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
            ],
            options={
                'verbose_name': 'assistant query',
                'verbose_name_plural': 'assistant queries',
                'ordering': ['-created_at'],
            },
        ),
    ]
