# Generated by Django 6.0.2 on 2026-06-15 14:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ShopItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('part', 'قطع غيار'), ('accessory', 'إكسسوارات')], db_index=True, default='part', max_length=12, verbose_name='النوع')),
                ('name', models.CharField(max_length=200, verbose_name='الاسم')),
                ('category', models.CharField(blank=True, default='', max_length=120, verbose_name='الفئة')),
                ('brand', models.CharField(blank=True, default='', max_length=120, verbose_name='الماركة')),
                ('price', models.BigIntegerField(blank=True, help_text='اتركه فارغاً لعرض «السعر عند الطلب»', null=True, verbose_name='السعر')),
                ('currency', models.CharField(choices=[('SAR', 'ريال سعودي SAR'), ('AED', 'درهم إماراتي AED'), ('USD', 'دولار USD'), ('EUR', 'يورو EUR'), ('KRW', 'وون كوري KRW')], default='SAR', max_length=3, verbose_name='العملة')),
                ('condition', models.CharField(choices=[('new', 'جديد'), ('used', 'مستعمل')], default='new', max_length=10, verbose_name='الحالة')),
                ('in_stock', models.BooleanField(default=True, verbose_name='متوفر')),
                ('is_featured', models.BooleanField(default=False, verbose_name='مميّز')),
                ('description', models.TextField(blank=True, default='', verbose_name='الوصف')),
                ('image', models.ImageField(blank=True, null=True, upload_to='site_shop/', verbose_name='الصورة الرئيسية')),
                ('fits_make', models.CharField(blank=True, default='', max_length=120, verbose_name='يناسب الماركة')),
                ('fits_model', models.CharField(blank=True, default='', max_length=120, verbose_name='يناسب الموديل')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'قطعة / إكسسوار',
                'verbose_name_plural': 'قطع الغيار والإكسسوارات',
                'ordering': ['-is_featured', '-created_at'],
                'indexes': [models.Index(fields=['kind', '-created_at'], name='site_shop_s_kind_faf86f_idx')],
            },
        ),
        migrations.CreateModel(
            name='ShopItemImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='site_shop/', verbose_name='صورة')),
                ('caption', models.CharField(blank=True, default='', max_length=200)),
                ('order', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='site_shop.shopitem')),
            ],
            options={
                'ordering': ['order', 'created_at'],
            },
        ),
    ]
