# Generated by Django 6.0.2 on 2026-06-15 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_shop', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='shopitem',
            name='origin',
            field=models.CharField(blank=True, choices=[('genuine', 'أصلي / وكالة'), ('aftermarket', 'تجاري / بديل')], default='', help_text='أصلي (وكالة) أو تجاري (بديل)', max_length=12, verbose_name='المصدر'),
        ),
        migrations.AddField(
            model_name='shopitem',
            name='part_number',
            field=models.CharField(blank=True, default='', help_text='رقم القطعة من المصنّع (MPN) أو رقم الوكالة OEM', max_length=80, verbose_name='رقم القطعة'),
        ),
        migrations.AddField(
            model_name='shopitem',
            name='part_number_norm',
            field=models.CharField(blank=True, db_index=True, default='', editable=False, max_length=80),
        ),
    ]
