# Generated by Django 6.0.2 on 2026-06-15 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_shop', '0002_shopitem_origin_shopitem_part_number_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='shopitem',
            name='external_id',
            field=models.CharField(blank=True, db_index=True, default='', max_length=120, verbose_name='المعرّف الخارجي'),
        ),
        migrations.AddField(
            model_name='shopitem',
            name='source',
            field=models.CharField(blank=True, db_index=True, default='', max_length=40, verbose_name='المصدر (استيراد)'),
        ),
    ]
