# Generated by Django 6.0.2 on 2026-06-24 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_shop', '0003_shopitem_external_id_shopitem_source'),
    ]

    operations = [
        migrations.CreateModel(
            name='ShopRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('part', 'قطع غيار'), ('accessory', 'إكسسوارات')], default='part', max_length=10, verbose_name='النوع')),
                ('car_vin', models.CharField(blank=True, default='', max_length=40, verbose_name='رقم الهيكل (VIN)')),
                ('car_description', models.TextField(blank=True, default='', verbose_name='وصف السيارة')),
                ('phone', models.CharField(max_length=30, verbose_name='رقم الهاتف')),
                ('email', models.EmailField(blank=True, default='', max_length=254, verbose_name='البريد الإلكتروني')),
                ('item_description', models.TextField(verbose_name='وصف القطعة/الإكسسوار المطلوب')),
                ('is_handled', models.BooleanField(default=False, verbose_name='تمت المعالجة')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'طلب قطعة/إكسسوار',
                'verbose_name_plural': 'طلبات القطع والإكسسوارات',
                'ordering': ['-created_at'],
            },
        ),
    ]
