# Generated by Django 6.0.2 on 2026-06-25 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_shop', '0004_shoprequest'),
    ]

    operations = [
        migrations.AddField(
            model_name='shoprequest',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='shop_requests/', verbose_name='صورة'),
        ),
    ]
